= Running Jamal in a Docker Container

This project contains files to support running Jamal in a docker container.


NOTE: This documentation describes how you can build the container from source, and how you can run Jamal in the container.
Building the container from the sources is only needed by the maintainers.
You can run Jamal from the container downloading from docker hub.

To run Jamal from docker, you have to issue the commands:


[source,bash]
----
docker build -t my_jamal_container .
docker run  --volume $(pwd):/home/jamal/q -it my_jamal_container /jamal args
----

You can use any container name you like instead of ``my_jamal_container``.

``args`` are the arguments you would normally pass to the ``jamal`` command.
Since the docker image sees only the mapped directory under the current working directory, you cannot use absolute paths.

Example:

[source,sh]
----
docker run  --volume $(pwd):/home/jamal/q -it my_jamal_container /jamal test.txt.jam test.txt
----

The command above will convert the file ``test.txt.jam`` to ``test.txt``.


When a release of Jamal is made, the multi-arch docker image is pushed to Docker Hub:

[source,sh]
----
docker login
docker buildx build --platform linux/amd64,linux/arm64 -t verhas/jamal:2.8.2 -t verhas/jamal:latest --push .
----

This will create and push images for both AMD64 and ARM64 architectures, tagged with the specific version and 'latest'.

If you want to use this container, you can download it from docker hub.

[source,sh]
----
docker pull verhas/jamal
docker run  --volume $(pwd):/home/jamal/q -it verhas/jamal /jamal args
----

or use a specific version:

[source,sh]
----
docker pull verhas/jamal:2.8.2
docker run  --volume $(pwd):/home/jamal/q -it verhas/jamal:2.8.2 /jamal args
----

NOTE: The examples use the latest release of Jamal, 2.8.2.
You can use any published version instead.

== Files in the module

=== `Dockerfile`

This file is the description of the docker image.
It is used by the `docker build` command to create the image.

[source,dockerfile]
----
FROM --platform=$BUILDPLATFORM alpine:latest
WORKDIR /home/jamal
RUN apk add --no-cache python3 py3-pip
COPY prebuild.sh /home/jamal/prebuild.sh
COPY build.sh /home/jamal/build.sh
COPY jamal /jamal
RUN sh /home/jamal/prebuild.sh
USER jamal
RUN sh /home/jamal/build.sh
CMD [ "/jamal" ]
----

It copies the three shell scripts to the container image and then it runs

* `prebuild.sh`

* `build.sh`

The third copied `jamal` script is the one that is run when the container is started.

=== `jamal`

This file is a shell script that will get copied to the container image as `/jamal`.

[source,sh]
----
#!/bin/sh
cd /home/jamal/q
java -cp "$(find "/home/jamal/.m2/repository" -name "*.jar" | tr '\n' ':')" javax0.jamal.cmd.JamalMain "$@"
----

It assumes that the current working directory is mapped to the directory
``/home/jamal/q
``.
That way the files passed as arguments to the ``docker run`` command will be passed to the `jamal` script.

=== `prebuild.sh`

This file installs all the needed programs that may be needed to run Jamal in the container.
Some packages are needed by some of the extra Jamal modules.

[source,sh]
----
#! /bin/bash

#
# Commands executed before the build as root
#

apk update
apk add --no-cache openjdk17 maven git fontconfig ttf-droid bash
addgroup JAMAL
adduser -G JAMAL -D -s /bin/bash jamal
chown jamal /home/jamal
chown jamal /jamal
chmod u+rx /jamal

# create the empty repo, this is where we will create the application
mkdir -p /home/jamal/.m2/repository
chown jamal /home/jamal/.m2/repository
chmod u+wxr /home/jamal/.m2/repository

# we do not need the prebuild script anymore
rm /home/jamal/prebuild.sh
echo "READY TO BUILD"
----

=== `build.sh`

This script builds Jamal.
The result of the build process creates the files in the local repository.
At the end of the build steps, the source code cloned from the repository is removed.

[source,sh]
----
#! /bin/bash

#
# Commands executed to build Jamal executed as user jamal
#

# clone the source into the 'build' directory
git clone https://github.com/verhas/jamal.git  build

# We do not need to compile and run the tests here, this is not development, it is deployment.
# After this command Jamal JARs and dependencies will be in the local Maven repository and nothing else.
cd /home/jamal/build || exit 1
mvn -Dmaven.test.skip=true install
cd ..

# we do not need the source any more, all the JAR files are in the local repo
rm -rf build

# we do not need the build script anymore
rm /home/jamal/build.sh
echo "DONE"
----


== Creating the Docker Image

To create the docker image you can use to run Jamal, you have to issue the command:

[source,sh]
----
docker build -t my_jamal_container .
----

Here you can use any name you like for your container.

== Running Jamal in a Docker Container

To run Jamal from docker, you have to issue the command:

[source,sh]
----
docker run  --volume .:/home/jamal/q -it my_jamal_container /jamal args
----

This will map the current working directory to the directory `/home/jamal/q` in the container.
This is assumed by the `/jamal` script.
Before starting Jamal the script sets the current working directory to `/home/jamal/q`.
That way, any file referenced on the command line will be found in the mapped directory.

NOTE: Mounting a directory using podman may be tricky regarding readability and may require additional options.

== Multi-architecture Builds

To create a Docker image that works on both ARM64 and AMD64 platforms:

=== Install and set up Docker Buildx:

[source,sh]
----
docker buildx create --name multiarch --driver docker-container --use
----

=== Build and push the multi-arch image:

[source,sh]
----
docker buildx build --platform linux/amd64,linux/arm64 -t yourusername/jamal:latest --push .
----

Replace `yourusername` with your Docker Hub username.

=== To use the multi-arch image:

[source,sh]
----
docker pull yourusername/jamal:latest
docker run --volume $(pwd):/home/jamal/q -it yourusername/jamal:latest /jamal args
----

The appropriate image for your platform will be automatically selected.