== Writing Built-In Macros for Jamal




Built-in macros in Jamal are the macros, which are implemented using Java code.
In this document we will describe how you can write built-in macros for your specific application.
The document assumes that you are familiar with Jamal macro structure and you know

* the difference between built-in and user defined macros in the Jamal file,

* how to define user defined macros

* what it means when a built-in macro uses the `@` character or the `#` in front of the macro name

* what is verbatim

* the macro evaluation order and how it can be modified using

* the `ident` and `eval` macros, and also the `!` and the backtick characters in front of the macros

* what are the different macro scopes

* how to export user defined macros to a higher scope

* how user defined macros arguments are separated and parsed

* generally, how to use Jamal.

[[helloworld]]
=== Creating a "Hello World" Macro

A "Hello, World!" example built-in macro is extremely simple.
You need the following dependency in your project:

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-api</artifactId>
    <version>1.7.3-SNAPSHOT</version>
</dependency>
----


In later versions, when we will do a bit more in our macros we will also need the dependency:

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-tools</artifactId>
    <version>1.7.3-SNAPSHOT</version>
</dependency>
----

This library has a transitive dependency to the library `jamal.api` so there is no need to specify both.
If you plan to use Java Platform Module System (JPMS) then you also have to add the

[source,java]
----
    requires jamal.api;
    requires jamal.tools;
----

directoves to your `module-info.java` file.
Having the project set up that way we can create our first nuilt-in macro.
The whole class is included in this document:

[source,java]
----
package javax0.jamal.test.examples;

import javax0.jamal.api.BadSyntax;
import javax0.jamal.api.Input;
import javax0.jamal.api.Macro;
import javax0.jamal.api.Processor;

public class HelloWorld implements Macro {
    @Override
    public String evaluate(Input in, Processor processor) {
        return "Hello, World!";
    }
}

----


The class has to implement the interface `Macro`.
This interface, as well as the other interfaces and classes imported are defined in the package `javax0.jamal.api`.
This interface requires us to create one method `evaluate()`.
This method gets the input text of the macro, a reference to the processor executing Jamal and it has to return a `String` that will be the content of the macro after evaluation.
In the example case we do not read the input and we do not use any service the processor can provide.
We will see in later chapters how to read and parse the input and also how to use the processor to access the executing environment.

The last step to use this macro is to create a text file and process it using Jamal.

The simplest way is creating a unit test to use the classes from the `jamal-testsupport` library.
It is recommended to use this package and to create unit tests for your macros.

To do that you have to add the dependency to your `pom.xml` file:

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-testsupport</artifactId>
    <version>1.7.3-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
----

Note that the scope of this dependency is `test` because these tools are needed only during unit test running.
You may also need to add a JVM command line parameter via the surefire plugin configuration, like the followings:

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version> ... actual version of the surefire plugin ... </version>
    <configuration>
        <argLine>
            --add-opens yourModuleName/packageName=ALL-UNNAMED
        </argLine>
    </configuration>
</plugin>
----

This is needed if your library uses JPMS.
When the tests are running they need access to your code using reflection and therefore you need to "opens" the package.
When you run the tests in the IDE it may ignore the JPMS settings and run your code as a plain library.
In that case the fact that the package is not open for the reflective access is not important.

[NOTE]
====
JPMS is complex and needs much more explanation than what can fit here.
Here I describe a few hints only, but it does not intend to teach you JPMS.
If you do not understand how JPMS works and how to use it you can get into trouble using it.
In that case you have two choices.

. Ignore the possibility to use JPMS, and create your macros as plan old classes in a plain old library, which will be available for Jamal from the `classpath`.

. Learn JPMS from excellent book of Nicolai: https://www.manning.com/books/the-java-module-system

I recommend the second.
====

Our test will be the following:

[source,java]
----
    @Test
    @DisplayName("Test that the HelloWorld built-in macro works")
    void macroWorks() throws Exception {
        TestThat.theInput(
            "{@use javax0.jamal.test.examples.HelloWorld}" +
                "{@helloworld}"
        ).results("Hello, World!");
    }

----

The first line declares the class as a macro.
The second line uses the macro, and the output will be the `Hello, World!`.

With this we are essentially ready with the hello world macro application.
There is one more topic, though, which is worth discussing here.

In the sample code we had to declare the class in the Jamal file as a macro to be used.
This is one of the three possibilities to make a Java class available for the Jamal code.
The second is to register the class for the standard Java service loader.

When a Jamal processor object is created it calls the Java service loader to find all the classes, which implement the `Macro` interface.
The returned list of instances are registered into the Jamal global macro registry and are available to be used for the Jamal processing.

The Java service loader can find a class if it is

* declared in the `module-info.java` module descriptor file as one providing the `javax0.jamal.api.Macro` interface, and/or


* the full class name is listed in the file 
`/src/main/resources/META-INF/services/javax0.jamal.api.Macro`

I recommend that you do both in case you use JPMS, because it will help test running inside the IDE, which may not use JPMS.
Having the class names listed in the 
`/src/main/resources/META-INF/services/javax0.jamal.api.Macro` file may also help applications that use your library as a normal JAR file and not as a module.

The module file will look something like this:

[source,java]
----
module jamal.test {
    requires jamal.api;
    requires jamal.tools;
    provides javax0.jamal.api.Macro with
        HelloWorld,
        Hello,
        Spacer,
        Array
        ;
}

----

Our module needs the `jamal.api` module, so we `require` it and we provide the `Macro` implementation.
After this out unit test will be the following:

[source,java]
----
    @Test
    @DisplayName("Test that the HelloWorld built-in macro is registered")
    void macroRegisteredGLobal() throws Exception {
        TestThat.theInput(
            "{@helloworld}"
        ).results("Hello, World!");
    }


----

Now we do not need to declare the class in the Jamal file, it is available in the global scope.

There is a third option to register a macro in the Jama processor.
The processor has an API and it is possible to register a user defined or a built-in macro programmatically.

=== Name of a Built-In Macro

In the <<helloworld,Creating a "Hello World" Macro>> chapter we did not discuss how the name of the macro is created.
We just created a class implementing an interface and then magically it was usable in the Jama source in the unit test with a reasonable name.
There is no magic.

The name of the macro can be defined in the macro `use` when a macro class is explicitly declared for use.
The syntax of the `use` macro is

    use [global] fully_class_name [ as macroname]

The parts between `[` and `]` are optional.

When the macro is registered via the service loader this option is not available.
In this case the name of the macro will be the string, which is returned by the method `getId()`.
This method is also part of the `Macro` interface, and it has a `default` implementations.

[source,java]
----
default String getId() {
    return this.getClass().getSimpleName().toLowerCase();
}

----

In our case the name of the class was `HelloWorld` which converts to `helloworld` all lower case as a macro name.
You are free to override the implementation of the default method, and there are real examples for that.
For example the `jamal-snippet` library macros `trimLines`, or `killLines` override the method `getId()`.

=== Handling the Input of the Macro

In the `HelloWorld` macro we totally ignored the input of the macro.
There are some built-in macros, like `comment` or `block` which deliberately do this.
It is not a good practice unless it has a purpose.

If we write another test, we can see that the macro really ignores its input.

[source,java]
----
@Test
@DisplayName("Test that the HelloWorld built-in macro works")
void macroIgnoresInput() throws Exception {
    TestThat.theInput(
        "{@helloworld the input is totally ignored}"
    ).results("Hello, World!");
}

----

==== Hello, Me Macro

The next macro we will write is one that will not simply greet the whole word, but rather the person, who we tell it to.
The code of the macro method in the class `Hello` will be the following:

[source,java]
----
public class Hello implements Macro {
    @Override
    public String evaluate(Input in, Processor processor) {
        return "Hello, " +in.toString().trim()+"!";
    }
}

----

It will use the `input`, convert it to string and cutting off the spaces from the start and from the end of the string it uses it as a name for the greeting.
The test is also straightforward and shows the direct use of the macro:

[source,java]
----
@Test
@DisplayName("Test that the Hello built-in macro works")
void macroWorks() throws Exception {
    TestThat.theInput(
            "{@hello Peter }\n" +
            "{@hello Paul}\n"
    ).results("Hello, Peter!\nHello, Paul!\n");
}

----

We are handling the simplest possible way  in this example.
We use it as it is, as a whole string, only cutting off the strings from the start and the end.
In the next chapter we will look at an example that handles the input in a more complex way.

=== Working with the Input: Example: Spacer Macro

Most of the macros use their input, and they use it in a more complex way.
To do that macros can parse, split up the input into smaller pieces that the code can afterwards work with.
To do that there are many possibilities.

For of all the interface `Input` extends the Java JDK `CharSequence` interface.
You can use all the methods defined there, they are implemented in the class.
The characters in the underlying structure are stored in a `StringBuilder`, and you can get direct access to that calling `getSB()`.

Built-in macros, however, rarely use these methods directly.
Instead, they use the static methods implemented in the `InputHandler`.

The `Input` object is essentially a character sequence, which also keeps track of the file name the characters came from and the actual line number and column position of the first character.
If you directly access the underlying `StringBuilder` and modify it then you may lose track of the line number and column position.

The class `InputHandler` defined methods that are safe to use for parsing the input.
The definite reference is the up-to-date JavaDoc.
In the following examples we will look at how to use some of these methods.

The following macro takes the input of the macro and inserts spaces between the characters.
That way it will convert

[source,text]
----
{@spacer this is
some text
}
----

to

[source,text]
----
t h i s   i s
s o m e   t e x t
----

The implementation of the macro is the following:

[source,java]
----
public class Spacer implements Macro {
    @Override
    public String evaluate(Input in, Processor processor) {
        InputHandler.skipWhiteSpaces(in);
        if (in.length() > 0) {
            final var result = javax0.jamal.tools.Input.makeInput("", in.getPosition());
            boolean lineStart = true;
            while (in.length() > 0) {
                if (!lineStart)
                    result.append(' ');
                lineStart = in.charAt(0) == '\n';
                InputHandler.move(in, 1, result);
            }
            return result.toString();
        } else {
            return "";
        }
    }
}

----

The very first thing the macro does is that it skips the white spaces.
It is customary to skip these spaces because one or more space has to be there after the id of the macro and they usually only separate the macro name and the content.
Some macros skip spaces only to the end of the line and in case there are more spaces, but on the next line then they are taken into account.
In this case all white spaces including new lines are skipped at the start of the input.
It is important to understand that the skipping process also takes care of the line number and the column position of the actual character.

The input keeps track of the file name, the line number and the column position of the character at the start of the character sequence.
These three things make a `Position` object.
The current position of an `Input` can be queried using the `getPosition()` method.

If the input contained only spaces then we skipped them all and in that case we simply return the empty string.
If there are characters in the input then we go through them one by one and we insert a space in front of each of them unless the character is at the start of a line.
To do this we create a new `Input` object, which is empty at the start and inherits the position of the original input.
Because `Input` is also a `CharacterSequence` we can easily get any character at a certain position calling `charAt()`.
We can also `move` characters from one input to the other.
The moving deletes the character from the `Input` `in` and it also modifies the current `Position` of the input.

Finally, the `result` is converted to `String` and is returned.

This macro interpreted the input as an array of characters.
Many times macros want to work with individual parameters.
In the next chapter we will look at an example how we should do that.

==== Splitting the Input

If you look at the core built-in macro `if` then you can see that it does not have a special syntax.
It just has three parameters and in case the first parameter is true, then it returns the second parameter, otherwise the third.
In case there are just two parameters then it results empty string in case the first parameter is false.
The syntax of the macro is:

[source]
----
{@if 'sep' condition 'sep' then result [ 'sep'else result] }
----

Here the `'sep'` is some kind of separator.
It can be a space, some non-alphanumeric character or some complex separator.
These three cases are handled by the method `getParts()`.
This method is defined in the class `InputHandler`.

This method skips the white spaces at the start of the input and then looks at the first character.
If it is a back-tick, then it fetches more characters until it finds a pairing back-tick character.
The string it fetches is used as a regular expression to split up the rest of the input.

If the first non-space character on the input is not a back-tick, but still a non-alphanumeric character then this character will be used as separator to split up the input.

Last, but not least if the first non-space character is alphanumeric then the input will be split up along the spaces.

The following example uses this method to implement a macro that can fetch one string from many based on an index.
For example



[source]
----
        {@array /1/x/aaa/z}


----

will select the second element, that is `aaa` from the array of `[ "x", "aaa", "z"]`.
The code of the macro is the following:

[source,java]
----
public class Array implements Macro {
    @Override
    public String evaluate(Input in, Processor processor) throws BadSyntax {
        final var pos = in.getPosition();
        final String[] parts = InputHandler.getParts(in);
        if (parts.length < 2) {
            throw new BadSyntaxAt("Macro Array needs an index and at least one element", pos);
        }
        final int size = parts.length - 1;
        final int index;
        try {
            index = Integer.parseInt(parts[0]);
        } catch (NumberFormatException nfe) {
            throw new BadSyntaxAt("The index in Macro array '"
                + parts[0]
                + "' cannot be interpreted as an integer.", pos, nfe);
        }
        if (index < 0 || index >= parts.length - 1) {
            throw new BadSyntaxAt("The index in Macro array is '"
                + parts[0]
                + "' but it should be between "
                + (-size) + " and " + (size - 1) + ".", pos);
        }
        return parts[index + 1];
    }
}

----

The macro calls the method `getParts()` passing only the input as one argument.
There is another version of the method that limits the number of the arguments.
Calling that the last element of the returned array will contain the rest of the string even if it could be split up more.
The macro implementation checks that there are enough number of parts and then converts the first part to integer.
This will be the index, the rest of the parts array are the values to choose from.
The code also checks the array bounds and throws exception in case there is an error.

When implementing a macro and there is an error the code has to detect it and it can throw a `BadSyntax` exception.
It is also declared in the interface.
The exception `BadSyntaxAt` is an extension of `BadSyntax`.
This second exception also contains the reference to the input location.

If the location of the error is not interesting inside the macro then it is good enough to throw a simple `BadSyntax` exception.
The processor catches that exception and converts it to a `BadSyntaxAt` exception that will reference the character at the very start of the macro.

=== General Structure of the `evaluate()` Method

=== Macros that are `InnerScopeDependent`

The macro evaluation order is detailed in the link:README.adoc[README] of Jamal.
When Jamal sees a built-in macro that starts with a `#` character at the start then it evaluates the content of it before invoking the macro itself.
For example

[source,text]
----
{#trimLines {@define margin=1}
{@snip sampleText}
}
----

will first evaluate the `define` macro resulting `margin` to become a user defined macro with the value `1`.
After that the `snip` macro will be evaluated and that way replaced with the snippet named `sampleText`.
Only when it is done starts the execution of thge macro `trimLines` that will shift the lines left or right with spaces so that there will exacly be ne space on the leftmost line.

The macro `margin` is defined in a local scope.
The scope starts with the opening `{` character of the macro `trimLines` and ends with the closing `}`.
If the implementation of the macro `snip` would query the macro register, it could see the value of the macro `margin` as `1`.

The question is whether the macro execution `trimMacro` sees `margin` as defined in itself or not.
Is the scope already closed when the execution of `trimLines` starts?

The answer is that it depends.

If the `Macro` implementing class also implements the `InnerScopeDependent` interface then the scope is open.
If it does not then Jamal closes the scope before starting the execution of the macro.

The macro `trimLines` implements this interface because it uses parameters.
The first few lines of the method `evaluate()` are the followings:

[source,java]
----
    @Override
    public String evaluate(Input in, Processor processor) throws BadSyntax {
        final var params = Params.using(processor).from(this).keys(Set.of("margin", "trimVertical")).parse(in);
        final var margin = params.getInt("margin").orElse(0);
        final var trimVertical = params.is("trimVertical");

----

It creates a `MacroReader`, which is a helper object.
It can help to "evaluate" user defined macros that have no parameters.
In case of those macros the evaluation simply means that the content of the macro is returned.
`trimLines` uses the macro `margin` to get the margin parameter.
It also queries the boolean value of the option `trimVertical`.

NOTE: The options are stored in `OptionsStore` objects.
This class implements the `Identified` interface and are stored in the same register where the user defined macros.
The name returned by `getId()` for these objects is ``options`.
Storing it in the registry has the advantage that this way options are scoped exactly as user defined macros.
If you say `{@options trimVertical}` inside a `{@trimLines ...}` it will have no effect outside of the execution of that `trimLine`.

Using user defined macros as parameters has several advantages and also some disadvantages.
When implementing a macro it is always a design decision how the macro should be constructed.
Some macro can be configured with parameters that the macro implementation parses.
The advantage of this approach is that this is simple and short when used.

Other macros can rely on user defined macro values.
The advantage of this approach is that the user may define these parameters global for the whole processing or for a larger scope.
For exaple `trimLine` could process and parese the first line of the macro for parameters to see if there is a `trimVertical=true` parameter,
This parameter, however, in this case should have been provided for each and every macro.
Defining `trimVertical` globally will instruct all use of `trimLines` to trim vertical.

Macros that rely on user defined macros or options as parameters should implement the interface `InnerScopeDependent`.
Macros that do not rely on those, should not.

=== Creating User Defined Macros

=== Creating Your Own User Defined Macro Implementation

=== Strategies to Register Built-In Macros

In this chapter I will explain the advantages, and the disadvantages of the two strategies that you can follow to register your built-in macros.
It is a more theoretical chapter with less example code.
You can skip this section and return to it later.


