#!/bin/sh

echo Integration test starts
mkdir -p .m2
mkdir -p .m2/repository
git clone https://github.com/verhas/jamal.git
cd jamal
mvn clean install
echo <<MESSAGE_END

+-----------------------------------------------------------------------------------------------------------------------
BUILD HAS FINISHED

INTEGRATION TESTS START...
+-----------------------------------------------------------------------------------------------------------------------
MESSAGE_END

cd jamal-maven-load
mkdir -p ~/.jamal
#!/bin/sh

echo "
testproperty=Peter Verhas' macbook
graphviz=/usr/local/bin/dot
#asciidoc.extension.log=false
asciidoc.extension.external.command=/Users/verhasp/.jbang/bin/jbang jamal@verhas -open=\{% -close=%\} $1 $2
maven.load.repo=https://repo1.maven.org/maven2/
maven.load.local=.m2/repository
maven.load.include=com.javax0.jamal:jamal-test:*
maven.load.exclude=.com.javax0.jamal:jamal-api:*" >~/.jamal/settings.properties

echo "chmod 0777 settings.properties"
chmod u+rx ~/.jamal
chmod 0777 ~/.jamal/settings.properties
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0707 settings.properties"
chmod u+rx ~/.jamal
chmod 0707 ~/.jamal/settings.properties
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0770 settings.properties"
chmod u+rx ~/.jamal
chmod 0770 ~/.jamal/settings.properties
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0700 settings.properties"
chmod u+rx ~/.jamal
chmod 0700 ~/.jamal/settings.properties
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0600 settings.properties"
chmod u+rx ~/.jamal
chmod 0600 ~/.jamal/settings.properties
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationSecure
echo "chmod 0777 ~/.jamal"
chmod 0777 ~/.jamal
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0707 ~/.jamal"
chmod 0707 ~/.jamal
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0770 ~/.jamal"
chmod 0770 ~/.jamal
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationNotSecure
echo "chmod 0700 ~/.jamal"
chmod 0700 ~/.jamal
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationSecure
echo "chmod 0500 ~/.jamal"
chmod 0500 ~/.jamal
mvn test -Dtest=javax0.jamal.maven.load.Integration_ConfigurationSecure
