== Jamal Releases



=== https://github.com/verhas/jamal/tree/1.10.3[1.10.3]

Support for ThinXML was added.

=== https://github.com/verhas/jamal/tree/1.10.2[1.10.2]

The position in error messages became hierarchical showing the position not only where the error is, but also where the actual file was imported, included from.
Snippets can be collected from resource and from teh web using file names that start with `res:` and `https://`.
Snippet collection still fails when trying to collect snippets from binary files, but the error message is more readable.
SnipCheck can be switched off using -Djamal.snippet.check=false
SnipLoad and SnipSave macros were developed letting the macro save and/or load snippets from an XML file
`string:xxx` macros now properly handle their arguments and do not use the whole input as an argument.
It makes difference in case of leading spaces.
Xml formatting is fixed.
Former formatting deleted the new lines from the output, that adversely affected CDATA content.
The new format fixes this and also adds a trailing `\n` at the end of the XML file.

=== https://github.com/verhas/jamal/tree/1.10.1[1.10.1]

The snippet library was extended with two new macros `xml:define` and `xml:insert`.
When an XML user-defined macro is used without an argument then the whole XML formatted is returned.

=== https://github.com/verhas/jamal/tree/1.10.0[1.10.0]

New macro `defer`, which evaluates its input after the whole input was processed in a closer.

Due to a bug, the backslash character did not escape the following newline after an `escape` macro (ironic).
Fixed.

The old-style macro evaluation is not available anymore. This significantly sped up the processing.
There were bug fixes for bugs that, in some situations, prevented the proper handling of `~/...` format file names.

Some environment variables did not have the system property pair.
Fixed.

The maven plugin, when used to convert a project to a Jamalized project, does not create `.mvn/extensions.xml` in the subdirectories anymore.

There is a new environment variable `JAMAL_DEV_PATH` and system property `jamal.dev.path`.
See the documentation.

A bug prevented file `include` in Windows in some special cases.
Fixed.

`snipline NAME` can be used to define a single line snippet without an end snippet.

Options `noUndefault` and `emptyUndef` are handled by macro evaluation.

`xmlFormat` works even in applications that embed Jamal in multi-thread.

`snip:check` is reworked, extended, and improved.

The core macro `if` now has several options, and it is possible to test numeric comparisons as well as string emptiness.

JUNIT dependency upped to 5.2.0

The handling of the `lenient` option has changed. From now on, `lenient` has to be a global option.

Environment variable handling was refactored, and the documentation was moved to the class defined in the API module.

JavaScript dependencies were upped to newer versions to avoid security issues.

Counter macros (from snippet) can be invoked with the parameter `last` to simply return the last value.

KillLine macro has to option `keep` that reverses which lines to keep and which lines to keep.

There is a new `snip:lineCount` macro that returns the number of lines in a snippet.

Options are not stored in option stores anymore.
Options are simple `Identified` objects stored along with the user-defined macros.
This also means that options can individually be exported, and the whole options store cannot be exported anymore in one.

=== https://github.com/verhas/jamal/tree/1.9.1[1.9.1]

The macro `escape` was extended.
Now if the macro name `escape` is followed by a `*` character then the escaping works multiple levels and is unescaped only when the whole processing is finished.
There is a new option for the Maven plugin of Jama.
If you specify the system option `jamalify` to be `true` then the plugin will create all the `.env` directories and `extensions.xml` files.
There was a bug in the macro `plantuml` in release 1.9.0, which prevented its working when no folder was defined explicitly.

=== https://github.com/verhas/jamal/tree/1.9.0[1.9.0]

Maven extension module is developed.
Using this module there is no need to preprocess `pom.xml.jam` or `pom.jam` files.
Maven automatically reads those files instead of the `pom.xml` using the extension.
Ruby scripts do not share the global variables any more.
It was a bug that the differently named Ruby scripts used the same set of global variables.
Ruby and Groovy macros can be configured using options and not only user defined macros.
`plantuml` macro also uses options and not only user defined macros to define the parameters like the image directory.
Built-in macros can have multiple names, and the assertion package immediately starts to use it so `equals` and `equal` ending denote the same macro.
Evaluate can evaluate macros in its input in a loop till all macros get evaluated.
Environment variable can be queried to throw exception when the variable is not defined.

=== https://github.com/verhas/jamal/tree/1.8.0[1.8.0]

SnipCheck was introduced to enforce snippet and documentation consistency.
There is a new package to check consistency.
This is the assertions package.
The macro statefulness is checked during macro load an in case a macro is stateful and not annotated to signal this then the macro load fails.
XML snippet reading bug (using CWD instead of document dir) was fixed.
Different dependencies were updated to the latest releases.

=== https://github.com/verhas/jamal/tree/1.7.9[1.7.9]

Fully reworked, redesigned, and functionally extended debugger client
`{@undefined }` macros can be `{@define ! ...}` defined

=== https://github.com/verhas/jamal/tree/1.7.8[1.7.8]

This release opens the debugger package, and so it can be used from Java::Geci. It still needs investigation why this is needed, though, but this patch solves this issue.

io:delete gives more meaningful error messages

TestWrite did not check that the output was really written. Fixed.

Various documentation and JavaDoc fixes.
SNAKE Yaml now uses the latest version and not an outdated one.
Build runs with Github action
Various tests and some production code were fixed so that the build runs also on Windows and Linux.

=== https://github.com/verhas/jamal/tree/1.7.7[1.7.7]

Markdown module was added with one single macro. Using this you can use markdown in JavaDoc files.
Macro can implement its own fetching, and that way now escape macro can also be aliased.
Option nl is removed, does not exist any more. Any \ after a macro escapes the next new line character.
For has new keyword from to iterate through a collection that a user defined ObjectHolder macro can provide.

=== https://github.com/verhas/jamal/tree/1.7.6[1.7.6]

Yaml XML macro extended to have attributes and CDATA in the output when you design a Yaml, especially for XML.
Macro `define` can specify optional parameters.
It is an error to use `:=` on a parameterless macro without `()` to avoid ambiguity.
Even I, who created the whole shenanigans, could not remember if `a:=` defines a global or a pure macro.

=== https://github.com/verhas/jamal/tree/1.7.5[1.7.5]

yaml can be exported as XML
debugger can handle breakpoints, UI was changed
yaml macros Add and isResolved are added
macro tests can now be written an jyt (Jamal Yaml Test) files


=== https://github.com/verhas/jamal/tree/1.7.4[1.7.4]

JavaDoc support
Yaml support
jamal-io module writing file and stdout and stderr
various bugfixes
collect can collect onceAs
verbatim user-defined macros
default macro can get the actual macro name
snippet trim macro can verticalTrimOnly
macro use can define alias for already existing macro


=== https://github.com/verhas/jamal/tree/1.7.3[1.7.3]

An interactive debugger was developed for Jamal transformation to follow the transformation step-by-step.
Jamal can be started using jbang.
command-line parameters are refactored and much more user-friendly.


=== https://github.com/verhas/jamal/tree/1.7.2[1.7.2]

New module integrating the Ruby scripting language
A bug is fixed that caused reporting the wrong error when there was an error inside an included file.


=== https://github.com/verhas/jamal/tree/1.7.1[1.7.1] Groovy module

This release includes a Groovy module that you can use to embed Groovy code into the Jamal input.

Closer objects are invoked in the order they were (first) declared.
bug fixed and makes it possible to use :a user-defined macros when USED and not only when defined
Test support can set the separators after the input is specified.
Cast tool was created in the tool module and use was moved from snippet to there.


=== https://github.com/verhas/jamal/tree/1.7.0[1.7.0]

New macro to undefine a user-defined macro.
Built-in macros can do post-processing where they can modify the final result.
jamal-snippet macro xmlFormat uses the new functionality and can format the whole document at the end
Embedding application can use a general 'context' that can also be used by the macros


=== https://github.com/verhas/jamal/tree/1.6.5[1.6.5]

Macro and module plantuml was developed


=== https://github.com/verhas/jamal/tree/1.6.4[1.6.4]

Snippet collection throws an error when a snippet is not closed but only in case the snippet is used.
Unclosed macro opening character reported line number is correct after a bug fixed that reported the last opened macro line number.
documentation about how to write a built-in macro was started
phantom parameters are handled correctly in case a macro does not have a parameter but there are zero string resulting macros evaluated in the parameters
InputHandler got a new startWith method
ScriptBasic module was reintegrated, following the release and is now part of the release
it is possible to define a user defined macro default which is used in case a macro is not defined. The real good use of it is when the user defined macro is defined using Java support and has special logic.


=== https://github.com/verhas/jamal/tree/1.6.3[1.6.3]

A new format for the for loop macro that lets you have values that contain the ) character inside.


=== https://github.com/verhas/jamal/tree/1.6.2[1.6.2]

trimLine was not included in the META-INF. It is now fixed.


=== https://github.com/verhas/jamal/tree/1.6.1[1.6.1]

File and directory macros were added to the snippet module.

=== https://github.com/verhas/jamal/tree/1.6.0[1.6.0]

This release contains two new modules: snippet support and test.
Macro try cleans the macro nesting stack properly, more possibility to recover after `try` catches an error
`import` does not allow dangling `begin` macros new macro `escape` was implemented to support macro opening and closing escaping documentation samples are generated on the file and not just copied from tests


=== https://github.com/verhas/jamal/tree/1.5.3[1.5.3]

Option `skipForEmpty` was implemented for `for` macro error message fixed in for


=== https://github.com/verhas/jamal/tree/1.5.2[1.5.2]

FEATURE: `for` macro is inner scope dependent.
FIX: multi variable `for` works properly when some of the values are empty strings FEATURE: multi variable `for` accepts less or more than required arguments with option lenient


=== https://github.com/verhas/jamal/tree/1.5.1[1.5.1]

Fix a bug that prevented include or import using relative file name in case the including/importing file was downloaded from the net via https protocol.


=== https://github.com/verhas/jamal/tree/1.5.0[1.5.0] NOT STABLE, DO NOT USE

Introducing macro 'try', the ! and

```
`
```

modification characters in front of built-in macros for built-in eval and ident functionality (see more in the README.md).

The for macro has a new syntax (backward compatible) and now it can have multiple loop variables.


=== https://github.com/verhas/jamal/tree/1.4.1[1.4.1]

There are new macros: env and jshell.
The default scripting engine is not JavaScript anymore, it is JShell.
bug fix over 1.3.0. DO NOT USE THAT RELEASE deployment fix from 1.4.0 which also failed to upload for mysterious reasons UPDATE: I have found the bug and fixed the pom for later releases.


=== https://github.com/verhas/jamal/tree/1.3.0[1.3.0] RELEASE IS CORRUPT, DO NOT USE

Failed release.


=== https://github.com/verhas/jamal/tree/1.1.0[1.1.0]

New release with extended extension macros and also including some bug fix.
The built-in macro can now depend on the inner scope defined user-defined macros.


=== https://github.com/verhas/jamal/tree/v1.0.2[v1.0.2]

This release introduces macros `for`, ˛`if`, `use` and supports trace creation.
At the same time it fixes several bugs.


=== https://github.com/verhas/jamal/tree/v1.0.1[v1.0.1]

Some minor bugs fixed.
This time parent pom is also released.


=== https://github.com/verhas/jamal/tree/v1.0.0[v1.0.0]

Initial release.