= Jamal dependencies versions check

This file can be used to check the Jamal dependency versions.
It loads the versions from the `version.jim` file and has a macro comparing it against the current Maven repo.
The rendering of this file is slow because it has to download the Maven metadata files from the Maven repository.
If all dependencies are up-to-date, then the output should not contain any `*[red]#NO#*` text with upgrade instructions.



== Jamal version check

* `OK`  `LAST_RELEASE` `2.8.1` 

== Dependencies


* `OK`  `LEVENSHTEIN_VERSION` `1.0.0` 

* `*[red]#NO#*`  `MAVEN_COMPILER_PLUGIN_VERSION` `3.13.0` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.


* `OK`  `MAVEN_JAVADOC_PLUGIN_VERSION` `3.10.1` 

* `OK`  `MAVEN_GPG_PLUGIN_VERSION` `3.2.7` 

* `OK`  `MAVEN_ASSEMBLY_PLUGIN_VERSION` `3.7.1` 

* `*[red]#NO#*`  `MAVEN_PLUGIN_API` `3.9.9` `*[red]#upgrade to 4.0.0-beta-5#*`
+
We do not upgrade to beta versions.

* `*[red]#NO#*`  `MAVEN_PLUGIN_ANNOTATIONS` `3.13.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `*[red]#NO#*`  `MAVEN_PLUGIN_PLUGIN_VERSION` `3.13.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `OK`  `SONATYPE_PLUGIN_VERSION` `1.7.0` 

* `OK`  `SUREFIRE_PLUGIN_VERSION` `3.5.1` 

* `*[red]#NO#*`  `MAVEN_SOURCE_PLUGIN_VERSION` `3.3.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `OK`  `APPASSEMBLER_PLUGIN_VERSION` `2.1.0` 

* `OK`  `MAVEN_DEPENDENCY_PLUGIN_VERSION` `3.8.1` 

* `OK`  `JUPITER_VERSION` `5.11.3` 

* `OK`  `MOCKITO_VERSION` `5.14.2` 

* `OK`  `JRUBY_VERSION` `9.4.8.0` 

* `OK`  `GROOVY_VERSION` `3.0.22` 

* `OK`  `OGNL_VERSION` `3.4.3` 

* `OK`  `SNAKEYAML_VERSION` `2.3` 

* `OK`  `JSON_ORG_VERSION` `20240303` 

* `OK`  `FLEXMARK_VERSION` `0.64.8` 

* `OK`  `APACHE_POI_VERSION` `5.3.0` 

* `OK`  `APACHE_POI_VERSION` `5.3.0` <- OOXML

[NOTE]
====
When upgrading the newer version, check that the dependency on


* `*[red]#NO#*`  `COMMONS_COMPRESS_VERSION` `1.26.2` `*[red]#upgrade to 1.27.1#*`

of the OOXML package is higher than 1.25.0

Version 1.25.0 has two vulnerabilities, CVE-2024-26308 and CVE-2024-25710.
The OOXML library version 5.2.5 depends on the vulnerable version.
The version 1.26.2 of the compress library is explicitly added to the `jamal-xls` module as a dependency.
It may not be needed when the poi-ooxml library also updates its dependency.
It has to be checked when stepping up from 5.2.5 to a newer version.
====


* `*[red]#NO#*`  `ASCIIDOCTORJ_VERSION` `3.0.0-alpha.1` `*[red]#upgrade to 3.0.0#*`

NOTE: Asciidoctor version after 3.0.0.-apha.1 use a different module name, not compatible with the old 2.X.X versions.
This causes class loading problems when the compatibility module is used to automatically detect which version of Asciidoctor is using Jamal as a preprocessor.
Since the version 3.0.0-alpha.1 is working fine with the old version, it can be used.
When the new Asciidoctor version is released and used as an IntelliJ plugin we will get rid of the compatibility module.


* `OK`  `JSCRIPTBASIC_VERSION` `3.0.0` 

* `OK`  `MAVEN_DOWNLOADER` `1.1.0` 

* `OK`  `SOURCE_BUDDY` `2.5.3` 
+
Version 2.5.2 changed the name of the module.
If we change the name of the module some tests that depend on prior versions of Jamal do not work.
To upgrade we have to remove the dependency from the snippet module and move the dependent macros to a different module.

* `*[red]#NO#*`  `MAVEN_CORE_VERSION` `3.9.8` `*[red]#upgrade to 4.0.0-beta-5#*`
+
We do not upgrade to beta versions.

* `OK`  `PLEXUS_COMPONENT_METADATA_VERSION` `2.2.0` 

* `OK`  `ASM_VERSION` `9.7.1` 

* `OK`  `ASM_TREE_VERSION` `9.7.1` 

* `OK`  `MARKDOWN_TO_ASCIIDOC` `2.0.1` 

* `OK`  `H2_VERSION` `2.3.232` 

* `OK`  `JSQLPARSER_VERSION` `5.0` 

* `OK`  `JSOUP_VERSION` `1.18.1` 