= Jamal dependencies versions check

This file can be used to check the Jamal dependency versions.
It loads the versions from the `version.jim` file and has a macro comparing it against the current Maven repo.
The rendering of this file is slow because it has to download the Maven metadata files from the Maven repository.
If all dependencies are up-to-date, then the output should not contain any `*[red]#NO#*` text with upgrade instructions.



== Jamal version check

* `OK`  `LAST_RELEASE` `2.8.2` 

== Dependencies


* `OK`  `LEVENSHTEIN_VERSION` `1.0.0` 

* `*[red]#NO#*`  `MAVEN_COMPILER_PLUGIN_VERSION` `3.13.0` `*[red]#upgrade to 4.0.0-beta-2#*`
+
We do not upgrade to beta versions.


* `OK`  `MAVEN_JAVADOC_PLUGIN_VERSION` `3.11.2` 

* `OK`  `MAVEN_GPG_PLUGIN_VERSION` `3.2.7` 

* `OK`  `MAVEN_ASSEMBLY_PLUGIN_VERSION` `3.7.1` 

* `*[red]#NO#*`  `MAVEN_PLUGIN_API` `3.9.9` `*[red]#upgrade to 4.0.0-rc-3#*`
+
We do not upgrade to beta versions.

* `*[red]#NO#*`  `MAVEN_PLUGIN_ANNOTATIONS` `3.13.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `*[red]#NO#*`  `MAVEN_PLUGIN_PLUGIN_VERSION` `3.13.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `OK`  `SONATYPE_PLUGIN_VERSION` `1.7.0` 

* `OK`  `SUREFIRE_PLUGIN_VERSION` `3.5.3` 

* `*[red]#NO#*`  `MAVEN_SOURCE_PLUGIN_VERSION` `3.3.1` `*[red]#upgrade to 4.0.0-beta-1#*`
+
We do not upgrade to beta versions.

* `OK`  `APPASSEMBLER_PLUGIN_VERSION` `2.1.0` 

* `OK`  `MAVEN_DEPENDENCY_PLUGIN_VERSION` `3.8.1` 

* `OK`  `JUPITER_VERSION` `5.13.0-M2` 

* `OK`  `MOCKITO_VERSION` `5.17.0` 

* `*[red]#NO#*`  `JRUBY_VERSION` `9.4.10.0` `*[red]#upgrade to 10.0.0.0#*`
JRuby versions 9.4.11.0 and later including the 10.X.X.X. versions are not compatible with the
IntelliJ Asciidoctor plugin

* `OK`  `GROOVY_VERSION` `3.0.24` 

* `OK`  `OGNL_VERSION` `3.4.7` 

* `OK`  `SNAKEYAML_VERSION` `2.4` 

* `OK`  `JSON_ORG_VERSION` `20250107` 

* `OK`  `FLEXMARK_VERSION` `0.64.8` 

* `OK`  `APACHE_POI_VERSION` `5.4.1` 

* `*[red]#NO#*`  `ASCIIDOCTORJ_VERSION` `3.0.0-alpha.1` `*[red]#upgrade to 3.0.0#*`

NOTE: Asciidoctor version after 3.0.0.-apha.1 use a different module name, not compatible with the old 2.X.X versions.
This causes class loading problems when the compatibility module is used to automatically detect which version of Asciidoctor is using Jamal as a preprocessor.
Since the version 3.0.0-alpha.1 is working fine with the old version, it can be used.
When the new Asciidoctor version is released and used as an IntelliJ plugin we will get rid of the compatibility module.


* `OK`  `JSCRIPTBASIC_VERSION` `3.0.0` 

* `OK`  `MAVEN_DOWNLOADER` `1.1.0` 

* `OK`  `SOURCE_BUDDY` `2.5.3` 

* `*[red]#NO#*`  `MAVEN_CORE_VERSION` `3.9.8` `*[red]#upgrade to 4.0.0-rc-3#*`
+
We do not upgrade to beta versions.

* `OK`  `PLEXUS_COMPONENT_METADATA_VERSION` `2.2.0` 

* `OK`  `ASM_VERSION` `9.8` 

* `OK`  `ASM_TREE_VERSION` `9.8` 

* `OK`  `MARKDOWN_TO_ASCIIDOC` `2.0.1` 

* `OK`  `H2_VERSION` `2.3.232` 

* `OK`  `JSQLPARSER_VERSION` `5.1` 

* `OK`  `JSOUP_VERSION` `1.19.1` 
This dependency is needed for the markdown to asciidoc conversion.
It is not used directly, and it is a transitive dependency of the markdown to asciidoc converter.
The transitive version of the dependency is too old and has security issues.
Therefore, here we override the version to the latest one.