= Jamal dependencies versions check

This file can be used to check the Jamal dependency versions.
It loads the versions from the `version.jim` file and has a macro comparing it against the current Maven repo.
The rendering of this file is slow because it has to download the Maven metadata files from the Maven repository.
If all dependencies are up-to-date, then the output should not contain any `*[red]#NO#*` text with upgrade instructions.




* `OK`  `LEVENSHTEIN_VERSION` `1.0.0` 

* `OK`  `MAVEN_COMPILER_PLUGIN_VERSION` `3.13.0` 

* `OK`  `MAVEN_JAVADOC_PLUGIN_VERSION` `3.6.3` 

* `OK`  `MAVEN_GPG_PLUGIN_VERSION` `3.2.4` 

* `OK`  `MAVEN_ASSEMBLY_PLUGIN_VERSION` `3.7.1` 

* `OK`  `MAVEN_PLUGIN_API` `4.0.0-alpha-13` 

* `OK`  `MAVEN_PLUGIN_ANNOTATIONS` `3.13.0` 

* `OK`  `MAVEN_PLUGIN_PLUGIN_VERSION` `3.13.0` 

* `OK`  `SONATYPE_PLUGIN_VERSION` `1.6.13` 

* `OK`  `SUREFIRE_PLUGIN_VERSION` `3.2.5` 

* `OK`  `MAVEN_SOURCE_PLUGIN_VERSION` `3.3.1` 

* `OK`  `APPASSEMBLER_PLUGIN_VERSION` `2.1.0` 

* `OK`  `MAVEN_DEPENDENCY_PLUGIN_VERSION` `3.6.1` 

* `OK`  `JUPITER_VERSION` `5.11.0-M1` 

* `*[red]#NO#*`  `MOCKITO_VERSION` `5.11.0` `*[red]#upgrade to 5.12.0#*`

* `OK`  `JRUBY_VERSION` `9.4.7.0` 

* `OK`  `GROOVY_VERSION` `3.0.21` 

* `OK`  `OGNL_VERSION` `3.4.3` 

* `OK`  `SNAKEYAML_VERSION` `2.2` 

* `OK`  `JSON_ORG_VERSION` `20240303` 

* `OK`  `FLEXMARK_VERSION` `0.64.8` 

* `OK`  `APACHE_POI_VERSION` `5.2.5` 

* `*[red]#NO#*`  `ASCIIDOCTORJ_VERSION` `3.0.0-alpha.1` `*[red]#upgrade to 3.0.0-alpha.2#*`

NOTE: Asciidoctor version after 3.0.0.-apha.1 use a different module name, not compatible with the old 2.X.X versions.
This causes class loading problems when the compatibility module is used to automatically detect which version of Asciidoctor is using Jamal as a preprocessor.
Since the version 3.0.0-alpha.1 is working fine with the old version, it can be used.
When the new Asciidoctor version is released and used as an IntelliJ plugin we will get rid of the compatibility module.


* `OK`  `JSCRIPTBASIC_VERSION` `3.0.0` 

* `OK`  `MAVEN_DOWNLOADER` `1.1.0` 

* `OK`  `SOURCE_BUDDY` `2.5.0` 

* `OK`  `MAVEN_CORE_VERSION` `4.0.0-alpha-13` 

* `OK`  `PLEXUS_COMPONENT_METADATA_VERSION` `2.2.0` 

* `OK`  `ASM_VERSION` `9.7` 

* `OK`  `ASM_TREE_VERSION` `9.7` 

* `OK`  `MARKDOWN_TO_ASCIIDOC` `2.0.1` 

* `OK`  `H2_VERSION` `2.2.224` 

* `OK`  `JSQLPARSER_VERSION` `4.9` 