= Jamal JAR Input Plugin

This library can handle files which are in JAR archives.
Using this library any link:../documentation/macros/include.adoc[`include`], link:../documentation/macros/import.adoc[`import`] or other macros that need to read a file can access JAR archives.

== Resource Name Format

To access a file from a JAR, the file name has to be formatted

.JAR resource format
****
`jar:file:` __path_to_the_JAR_file__ `!` __path_inside_the_jar_to_the_file__
****

* The `jar:file` part is a fix prefix, like in the case of `res:` reading Java resources, or `https:` reading web files.

* The __path_to_the_JAR_file__  is the jar file.

* The __path_inside_the_jar_to_the_file__ is the path inside the JAR file to the actual file.

.Examples
[%collapsible]
====
****
Example:

[source]
----
{@include [verbatim] jar:file://C:/Users/PincoPalino/myJar.jar!/Bing.txt}
----
====

The JAR file simply has to be on the class path, and Jamal will find it using the service loader facility.
The standard modules embedding Jamal do it.