
= Integration Tests using Docker/Podman

This directory contains the integration tests.
Integration tests are executed using Docker containers.

To run them

----
start your docker daemon
cd .../IT_DOCKER
./test.sh
----

WARNING: Do NOT run ``integrationtest`` from this directory.
It is to be executed inside a container.
If you run it from here, it will mess up the directory cloning the Jamal repository, creating a local repo `.m2/repository` and other nasty things.
To avoid that, it checks if it is inside a container and stops when it feels it is not.



## Executing the integration tests

The tests can be created and executed using the `test.sh` script.
This script creates the test scripts from the local Jamal sources, builds the Docker image and runs the tests.

Prerequisites:

* Docker must be installed and the daemon running, or

* Podman must be installed and the virtual machine running on Apple architecture

* The script must be executed from the directory containing the `integrationtest`.

* The docker/podman instance running should have internet connection

** to GitHub for cloning Jamal source

** Maven central for building Jamal, downloading the dependencies

Note that the processing of the Jamal sources to prepare the integration test is done with the locally installed development version, but the integration tests will be executed by cloning the Jamal repository from GitHub.

## Integration tests implemented

This section describes the integration tests implemented.
Each subsection is a test, part of, and executed by the `integrationtest` script.


### Basic Maven Compilation

The first step is to build Maven.
Because the container does not have a local repo it will provide a fresh build downloading all dependencies from central.

### Setting Security

When the macro `maven:load` is used, it requires that the configuration in `~/jamal` is secure.
It must not be read or modified by other users.
The test sets the file permissions to the directory and the configuration file in different ways and runs tests.

### Command Line execution

The test runs the command line tool `jamal` with different parameters.