== Jamal PlantUML Diagrams
:imagesdir: images

PlantUML's integration supports PlantUML descriptions to be embedded into any Jamal file.
The macro `plantuml` can convert the content passed to it to an image file and return the file's reference.
This way, Jamal will replace the PlantUML description in the processed output with the image reference to the file generated on the file.

Jamal also saves the information about the diagram generation in the cache directory structure.
It generates the images only when there is a need for them.
If the picture did not change since PlantUml created the image, then PlantUML will not run to save CPU clocks.

=== Use of the `plantuml` macro

The package contains one macro named `plantuml`.
The syntax of the macro is

[source]
----
{@plantuml image_file_name

content of the diagram
}
----

The macro interprets the characters following the macro's name as the name of the output file till the end of the line.
The rest of the macro lines is the content of the plant UML diagram descriptions.

For example, the following sample:

[source]
----
{@define pu$folder=images/}
{@plantuml first_image1.svg
@startuml
Bob -> Alice : hello
@enduml
}
----

will create the file `first_image.svg` in the folder `images` and will result in the output as

[source]
----
first_image1.svg
----


Having the name of the output file, however, does not help much unless we use it.
You can convert it to an image reference with some macros, but the macro `plantuml` also helps.
The user-defined macro `pu$template` defines the template for the returned string.
The placeholder `$file` in the template means the name of the actual file.

The same example modified a bit is the following:

[source]
----
{@define pu$template=image::$file[]}
{@define pu$folder=images/}
{@plantuml first_image2.svg
Bob -> Alice : hello
}
----

will result in an image reference, as in

[source]
----
image::first_image2.svg[]
----


and if we use it in an Asciidoc file it will look like the following:



image::first_image3.svg[]

The PlantUml texts usually start with a `@umlstart` and finish with an `@enduml` line.
Because this is almost always there, the macro `plantuml` inserts these lines if they are missing.
To be precise, it checks if the first line of the diagram description starts with the `@` character.
If it does, then it assumes that the lines are already there.

Some diagrams start with slightly different directives.
For example, YAML diagrams start with the `@startyaml` and end with the `@endyaml` lines.
Jamal cannot figure out the type of the diagram; therefore, if the start and end lines are not `@startuml` and `@enduml`, respectively, you have to include these lines in the body of the macro.

=== Formatting, Folder and Template

User-defined macros can control the behavior of the macro `plantuml`.
These macros all start with the prefix `pu$` that stands for `p` plant and `u` as UML.
These parameters can also be defined as options between `(` and `)` characters.
In the case of this macro, this is not important because the parameters, the folder, and the format template do not usually change from diagram to diagram.

[NOTE]
====
The options can be used as `{@plantuml (format="$file") ... }` inside the macro.
The macros `pu$...` can also be defined inside the `{@plantuml ...}` macro.
You can see examples of that in the unit tests.
In that case, the value of the `pu$...` macro is local for the `plantuml` macro where it is defined.
When the value is defined as an option, the value is local for the macro.
The name of the macro and the alias can also be used as an option name, but the alias cannot be used as a macro.
(It can be used as a macro, but there is no effect to the macro `pmantuml`.)
====

The macros/options are:

* `pu$folder` (alias `folder`) can define the directory where the graphical file gets saved.
The default value is the directory where the document itself is.
It is recommended to specify a particular folder for the purpose, and in the case of Asciidoctor files, use the `imagesdir` attribute.
Note that the folder specification can be absolute or relative to the current Jamal file.
If a Jamal file from a different directory includes the current Jamal file, it may cause a problem.
In such a case, using the absolute file name via the `directory` macro from the Jamal Snippet library is recommended.

* `pu$format` (alias `format`) should specify the format of the output file.
It should be the file format, `SVG` or `PNG`.
The code consults the PlantUML enumeration `FileFormat` therefore, Jamal can use any format supported by the used version of PlantUml.

* `pu$template` (alias `template`) specifies the format for the result of the macro.
The placeholder `$file` means the file's name as specified in the macro in this template.
The default value is to return the file name itself.

[NOTE]
====
You can decide to write into your Jamal file the reference to the picture generated.
For example, you want to write:

    {@plantuml myimage.svg
         ... my diagram ...
    }
    image::myimage.svg[]

in the source code.
This approach's advantage is that once Jamal transformed the source through Jamal, you can already see in a WYSIWYG editor the diagram while editing.
In this case, you should

    {@define pu$template=}

so that the value of the macro `plantuml` is an empty string.
====

=== Error Handling

During the diagram's conversion, the macro will throw a `BadSyntax` exception if there is an error.
That means that unless you enclose the `plantuml` macro into a `try` macro, the processing of the file will stop with an error.
An error can be the wrong use of the macro, like specifying an invalid format.
In this case, Jamal does not generate the output file.
Another type of error is when the generation of the diagram is erroneous.
In this case, PlantUml creates a diagram; it just shows an error.
In this second case, the macro `plantuml` first saves the generated diagram to the output file and only after that signals the error.


=== Library Dependency

Jamal PlantUml integration comes in a separate library.
To use the macro, you need the JAR file on your classpath and all dependencies transitively.
The maven coordinates for the Jamal module are:

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-plantuml</artifactId>
    <version>1.12.2</version>
</dependency>
----

The module has a dependency on the PlantUml binaries, and the currently used version of PlantUml is 1.2022.4:

[source,xml]
----
<dependency>
    <groupId>net.sourceforge.plantuml</groupId>
    <artifactId>plantuml</artifactId>
    <version>1.2022.4</version>
</dependency>
----

If you want to use a different version of PlantUml, you can specify the version in your `pom.xml` file directly.


=== Caching

Converting a diagram to graphical representation is resource-intensive.
It is typical to convert a Jamal file during document development many times.
Most of these times, most of the diagrams do not change.
The `plantuml` macro uses caching to avoid the conversion of the already converted source text.

There is no need to understand how caching works.
It is automatic.
In this chapter, we describe the algorithms and behavior of the macro related to caching.
You may need this information in case you need to troubleshoot the diagram generation.

The most important rule `plantuml` follows is the following:
If the desired output file does not exist, it will be created, no matter what is in the cache.
If you have a problem with the caching behavior of the `planuml` macro, delete the generated diagrams.

The Jamal cache is by default in the directory `~/.jamal/cache`.
The location can be configured using environment variables.
The cache directory has to be created manually, or else no caching will occur.
Jamal creates any subdirectories needed under the cache directory.

When the diagram conversion is executed, the macro saves the source text into the Jamal cache.
The directory will reflect the full path of the output file.
For example on a MacOS the directory will be something like `~/.jamal/cache/https/Users/verhas/projects/jamal/images/`.

Note that the file will have the name of the generated diagram file, for example, `mydiagram.svg`, but the content will be the UML text source.

When the macro sees a generated output file and a cached file, it checks the cached file's content.
The generation step is skipped if it is precisely the same as the one currently converting one.

Every cached file has a `properties` file paired with it.
This properties file will contain a boolean property called `error`.
If this property is `true`, then the macro will throw an exception.
This way, an error will not go undetected because the cache signals no reason to rerun the conversion.

=== Other Similar Solutions

When you are using Asciidoc or Markdown, you may ask why use Jamal and this module instead of using the document native integration.
There is no final and ultimate answer to that.
You have to decide the advantages and disadvantages of the different approaches and select the one that fits you the best.

First and foremost, you can use the full power of Jamal.
You can use macros, modules that help you make a document maintainable.

Using Jamal, you get an output file that does not require any plugin to handle PlantUml.
The plugin to render PlantUml may not be available on the system where the rendering executes.
By the time I write this, GitHub and GitLab do not support PlantUML.

Using the Jamal macro, you get the image files, and the generated Jamal output is free of the UML source code.
You do not run into problems, like how to hide the UML Text in Markdown to not appear in the output.

Some converters require that a PlantUml server is running in the background.
Jamal's `plantuml` macro uses the PlantUml library and does not need a running server.
It does the conversion in JVM without starting a new process.
Jamal also caches the conversion.
Therefore, the conversion is relatively economical.
