= Jamal Python Macros

Python integration module for

This macro package can be used to create built-in macros defined in Python.
A Python defined macro is a function ``def``-ined.
The name of the macro is the name of the function.
The function gets one ``str`` argument.
The result of the macro is what the function prints to the standard output.

For example:


.Jamal source
[source]
----
{@python
def chubakka(input):
    print("Chubakka says: " + input, end='')
}
{@chubakka Boaaaa}
----

will result in:

.output
[source]
----
Chubakka says:  Boaaaa
----


To successfully use this macro, you must have a Python interpreter installed.

The macro package is part of the

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-py</artifactId>
    <version>2.8.3-SNAPSHOT</version>
</dependency>
----

macro package, but it is also part of the standard builds, so you can just use it in IntelliJ, AsciidocFX or on the command line etc.

== Macros Implemented



=== `python`

The macro `python` is used to define a Jamal built-in macro using Python.
For example, the following call will define the built-in macro ``chubakka``.

.Jamal source
[source]
----
{@python
def chubakka(input):
    print("Chubakka says: " + input, end='')
}
{@chubakka Boaaaa}
----

The first line of the code

    def chubakka(input):


defines a function.
The function name is the macro name.
The parameter `input` is a string (``str``), which follows the macro name, in the example above `Boaaaa`.
The result of the macro is what the Python code prints to the standard output for both the `@python` and the created new macro.

[NOTE]
====
The regular expression to find the name of the macro is

  def\\s+(\\w[a-zA-Z0-9]*)\\s*\\(.*\\)\\s*:\\s*\n

====

Sometimes you cannot rely on the Python code structure to let the macro figure out the macro and function name.
You may even want to have the name different.
In that case you can use the `id` and `function` parops.
Using `id` or `id ` and `function` together will skip the pattern matching seeking for function head.

.Jamal source
[source]
----
{@python (id=OO7 function=agent)
# This is a code that has many methods, and thus we cannot use the built-in pattern mathcing
def name():
    print(" Bond",end='')
def agent(txt):
    name()
    print(",",txt,end='')
    name()
print("done")
}{@OO7 James}
----

will result in

.output
[source]
----
done
 Bond,  James Bond
----


As you can see the macro `@python` executes the code and the result is the output of the code.

The reference list of the parops for this macro is the following:

* `id`, alias `name`, alias `macro`
defines the name of the macro.
If this is not defined, the macro will try to use pattern matching, finding the `def XXXX(txt):` structure in the code.
* `function`, alias `def`
defines the name of the function if it is different from the name of the macro.
It is an error using this parop without using `id` (or one of its aliases).
* `execute`
signals that the Python code is to be executed, and it does not contain any macro defining function.
Using this parop will simply execute the code without trying to find a macro function.
You cannot use this parop together with `id` or `function`.
* `directory`, alias `dir`, alias `wd`
the working directory where the execution should start.
If there is a `venv`, or whatever directory name is defined in the `venv` parop under this directory,
then Python will run in a virtual environment.
This option is ignored on later calls when the interpreter was already launched.
* `venv`
specifies the directory name of the virtual environment.
The default value is `venv`.
This option can only be used together with the option `directory`.
* `close`
defines that the code is to be executed when the interpreter exists.
The last line of the python code has to be `sys.exit(0)` or whatever exit code you desire, or else
the interpreter process will be killed forcefully.
You cannot use this parop together with `execute`, `function` or `id`.
When this parop is used, the return value of the method is an empty string.

The parops are all aliases technically.
It means that you cannot define them as user-defined macros.
They have to be present on the macro between `(` and `)` characters.


== Python Location

To use these macros, there must be an installed Python interpreter on the system.
The macro will try to locate the interpreter searching on well-known locations.

If there are multiple interpreters available, it will select the one with the highest version.
If there are multiple interpreters of the same version, the first found will be used.

These locations are the following:

=== Windows

                    C:\\Python310\\python.exe
                    C:\\Python39\\python.exe
                    C:\\Python38\\python.exe
                    C:\\Python37\\python.exe
                    C:\\Python36\\python.exe
                    C:\\Python35\\python.exe
                    C:\\Python34\\python.exe
                    C:\\Python33\\python.exe
                    C:\\Python32\\python.exe
                    C:\\Python31\\python.exe
                    C:\\Python30\\python.exe
                    LOCALAPPDATA + \\Programs\\Python\\Python310\\python.exe
                    LOCALAPPDATA + \\Programs\\Python\\Python39\\python.exe
                    LOCALAPPDATA + \\Programs\\Python\\Python38\\python.exe
                    LOCALAPPDATA + \\Programs\\Python\\Python37\\python.exe


=== macOS

                    /usr/local/bin/python3
                    /usr/bin/python3
                    /opt/homebrew/bin/python3
                    /usr/local/bin/python
                    /usr/bin/python
                    /opt/homebrew/bin/python



=== Linux

                    /usr/bin/python3
                    /usr/local/bin/python3
                    /bin/python3
                    /usr/bin/python
                    /usr/local/bin/python
                    /bin/python



=== Common

If the above operating-system specific locations fail, then the code will try

* `python3`,
* `python`,
* `py`

from the PATH.

=== Configuration

If the environment variable ``JAMAL_PYTHON_INTERPRETER`` is defined then the value of it will be used and the whole search for Python interpreter is skipped.
It is recommended to configure the interpreter this way because the search can use significant processing power starting the different interpreters as separate processes querying their version.

=== Security

Executing arbitrary Python programs when opening a document without restrictions can be risky.
You might download an untrusted document:

* from a website,
* from a Git repository,
* or from an extracted archive.

You wouldn't want such documents to automatically execute Python code.
To prevent this, Python code will only run if a special approval file is present:

* in the directory containing the Jamal file with the `{@python ...}` macro, or
* in the project's root directory.

The name of this approval file is ``.python.sentinel``.
It also has to have the security settings so that only the user can read the file.
In other words, the POSIX permission of the file has to be `0400`.
If the required file is missing or the permission is not as required the `{@python ...}` macro will result in an error message.

This message will include the necessary commands to create the file on your system.
For example:

.Sample error message when editing this document (path edited)
[source,text]
----
Approval file does not exist: Approval file required at: touch /Users/.../jamal/jamal-py/.python.sentinel; chmod 400 /Users/.../jamal/jamal-py/.python.sentinel
       or
touch /Users/.../jamal/.python.sentinel; chmod 400 /Users/.../jamal/.python.sentinel
----

The error message specifies the required file name and instructs you to set the correct file permissions.
The approval file must have POSIX permissions set to `+0400+`, ensuring that only the file owner can read it.
If the permission differs, the `{@python ...}` macro will not function.

Enforcing this permission safeguards users when deploying a downloaded project in the same directory, preventing unauthorized execution.
Actions like checking out a Git repository or extracting an archive typically do not set permissions to `0400`, adding an extra layer of security.