[WARNING]
--
* There were 2 syntax errors processing the Jamal input:
* 1. There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
* 2. There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8
--
[WARNING]
--
* There were 2 syntax errors processing the Jamal input:
* 1. There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
* 2. There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8
--
{%@comment of %}\
{%@comment this file is converted using runtime information from the module, and therefore it cannot be processed by the asciidoctor plugin: off, as above%}\
= Jamal Ruby integration module
{%@import res:jamal.jim%}\
{%@snip:collect from="src/test/java/"%}\
{%@snip:collect from="src/main/java/"%}\
{%@snip:collect from="../jamal-snippet/src/test/java/javax0/jamal/documentation"%}\

{%#counter:define id=macroChapter {%@define format=$roman. %}%}

Using this integration module, you can mix Jamal macro text with Ruby code snippets.
To use this module, you have to add the dependency to your Maven project, as:
{%@snip:xml pom=pom.xml%}\
{%#define VERSION={%pom /project/version/text()%}%}\

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-ruby</artifactId>
    <version>{%VERSION%}</version>
</dependency>

----
 Following that you can use the macros
{%@ruby:property $chapters = 0%}{%@comment count the chapters and then we can use this in the text where we says how mny macros are there%}
{%@define chap($x)=. <<$x,`ruby:$x`>> {%@ruby:import
$chapters++%}%}

{%chap eval%}
{%chap import%}
{%chap shell%}
{%chap property%}
{%chap closer%}{%#define chapNR={%@ruby:eval $chapters%}%}

macros.

== Macros implemented in the package

The macros implemented in this package make it possible to embed Ruby scripts into the Jamal source code.
Ruby is an object-oriented scripting language that has JVM implementation with compelling features.
Using Ruby as a scripting language may be an alternative to using the Java provided and Jamal core integrated JShell.
In some cases, an embedded Ruby script may also serve your purpose instead of writing a Java built-in macro.

In this chapter, we will discuss every macro defined in the package with examples.
The examples are automatically generated into the Asciidoc file, similarly to the samples in the other documentation files.
The difference is that in the case of the main `README.adoc` and the other files, the conversion uses two Java-defined macros.
In this case, we do not use these macros.
Instead, Ruby scripts perform the tasks, eliminating the need to write a separate class to implement the user-defined macros `sample` and `output`.

The chapter <<Sample,Sample>> describes this process as a non-trivial example for using the Ruby engine.

The package defines {%chapNR%} macros.

The macro `ruby:eval` evaluates a simple expression.
`ruby:import` can import Ruby code.
`ruby:property` can set or get Ruby variables.
`ruby:shell` can execute more complex Ruby code.
Finally, `ruby:closer` makes it possible to implement closer scripts.

The different macros use Ruby `ScriptingContainer` objects to execute the Ruby scripts.
These container objects are automatically created and named.
{%@define ShellObjects=ShellObjects%}{%@define ShellObjectsTitle=Using Multiple Container Objects%}\
Their use is detailed in the chapter <<{%ShellObjects%},{%ShellObjectsTitle%}>>.
If you do not want to use multiple, separated Ruby containers, you do not need to worry about the container objects.
Jamal will create one upon using one of the Ruby macros and utilize it throughout the Jamal file.

{%@define chap($x)=[[$x]]
==== {%macroChapter%}`ruby:$x`
%}

{%chap eval%}

The macro `ruby:eval` uses its whole input as a ruby expression and evaluates it.
For example the following macro call:
{%sample/
{@ruby:eval 1+1}
%}

will result:

{%output%}

{%chap import%}

This macro can import a Ruby file into the shell.
The macro has two forms:

* `{@ruby:import fileName}`, and

* the format
[source,text]
----
{@ruby:import

}
----

In the first case, Jamal can import the named file.
The file's name can be relative to the input file containing the import macro, can be absolute, or can have the prefix `res:` or `https://`.
The file names starting with the prefix `res:` are resource files and must be available on the classpath.
The files with the prefix `https://` are downloaded from the net and are cached.

The name resolution and file access, download, and caching are made precisely the same way as in the case of the built-in macro `import`.
For more information about that, please read the link:../README.adoc[main readme] file of Jamal.

In the second case, if no characters denote a file name on the first line after the macro name, Jamal will import the macro content.

The shell will evaluate the content.
This evaluation tries to create a return value, ignored in the case of the `ruby:import` macro.
However, if the content does not have an evaluable return value, the shell will throw an exception.
This exception is hard to ignore because the Jamal macro implementation cannot comprehend if this is a final value evaluation error or an actual Ruby error.
If there is an actual Ruby error, then the macros enclose it into a Jamal syntax error and report it that way.

The macro appends a `\n''` string after the Ruby script to avoid the final evaluation errors.
It will result in an empty string, the macro `ruby:import` results.

Use `ruby:import` if you do not want to include the result of the script into your output or if the script is in a separate Ruby file.

{%chap shell%}

You can execute a script using `ruby:shell` and get the result as a string into the Jamal output.
The format of the macro is

[source,text]
----
{@ruby:shell scriptname.rb
script content
}
----

The `scriptname.rb` part is optional.
Only error reports use this name.
Getting an error message makes it simpler to find which Ruby script fragment was throwing up.
If this part is missing, the macro will use the name of the actual Ruby shell with the `.rb` extension.
Again: this is not a reference to any actual file name; it is only for the error messages.
Using `something.rb` is just a good convention that you may like to follow.

The `script content` will be evaluated, and the final result will be the result of the macro.
Use this macro if your script is longer and not just a simple one-liner, in which case you can use the macro `ruby:eval`.

{%chap property%}

This macro sets and gets Ruby variables.
Ruby containers can communicate with the embedding application, which is Jamal in our case.
The embedding application can set and get variables of the Ruby script.

For example, the following sample

{%sample/
{@ruby:property $myProp=(to_i)55}
{@ruby:eval $myProp+45}
%}

and it will result

{%output%}

You can also fetch the value of a variable set before by the Ruby script or by the `ruby:property` macro:


{%sample/
{@ruby:eval $yourProp=133}
{@ruby:property $yourProp}
%}

will result

{%output%}

once by the result of the `ruby:eval` and once as the `ruby:property` also fetched this value.

Setting the value, you can specify the type of the property.
In the sample above we wrote

{%sample/
{@ruby:property $myProp=(to_i)55}
%}

In that code `(to_i)` is a conversion and the `ruby:property` macro will evaluate, and act upon it.
The `(tp_i)` converts the text following it to a Fixnum value.
You can use other type conversions following the `=` between `(` and `)`.

The possible types are limited to

* `to_i` to convert the string to a Fixnum

* `to_f` to convert  the string to Float

* `to_s` to convert  the string to string.
This is the default conversion in case you do not specify any.

* `to_r` to convert the string to rational.
In this case, the number has to be `X/Y` formatted.

* `to_c` to convert the string to complex number.
In this case, the number has to be `R+Ii` formatted, where `R` and `I` are integers or floating-point numbers, and `i` is the letter i (lower case).

* `to_c/i` to convert the string to a complex integer number.
It is the same as `(to_c)`, but the real and the imaginary parts of the number have to be integers.

* `to_sym` to convert the string to be a Ruby symbol.

The casting type has to be enclosed between `(` and `)` characters, no spaces are allowed.
The default is to set the property to be a string.
The casting `(to_s)` is available if you want to emphasize that the value should be handled as a string.
It may also happen that you want to pass a *string* that starts with the characters `(to_i)` or something similar.

Some examples:

{%sample/
{@ruby:property complex=(to_c)66+13i}
{@ruby:eval complex * complex}
%}

will result

{%output%}

{%sample/
{@ruby:property complex=(to_c/i)66+13i}
{@ruby:eval complex * complex}
%}

will result

{%output%}

{%sample/
{@ruby:property ratio=(to_r)66/13}
{@ruby:eval ratio * ratio}
%}

will result

{%output%}

{%chap closer%}

Using the macro `ruby:closer`, you can create a so-called closer script.
You can use the script to modify the whole output after the processing of Jamal has finished.

The format of the macro is

[source,text]
----
{@ruby:closer ruby script}
----

The only argument to the macro is the closer Ruby string.
It can be multi-line, and Jamal executes it after processing the whole Jamal file.
Before starting the script, the global variable `$result` will be set.
It will contain the result of the Jamal processing.
The content of the global variable `$result` is a Ruby string.

The closer script should result in a string that will replace the original result.

You can specify any number of closer scripts using different or the same Ruby shell.
Jamal will invoke all scripts one after the other in the order they were defined in the Jamal source.

{%sample/
Hi, I am the content of the Jamal file.
{@ruby:closer "I do not care what the original text was, replace it with this one."}
The closer will kill me.
%}

will result

{%output%}

[[{%ShellObjects%}]]
=== {%ShellObjectsTitle%}
{%#define defaultShellName={%@snip defaultShellName /"(.*)"/%}%}\
{%#define shellNamingMacro={%@snip shellNamingMacro /"(.*)"/%}%}\

If you do not specify any shell object, it will be created automatically using the name `{%defaultShellName%}`.

Jamal stores Ruby shell objects along with the user-defined macros.
It has two consequences.

* If there is a user-defined name with the same name as the Ruby shell name, the one defined later will overwrite the other.

* The Ruby shell objects are available only within their scopes precisely the same way as user-defined objects.
You can also export them.

Note that the default name starts with `:`; therefore, this is a global name, available in all scopes.
It is a feature to ease the use of the Ruby shells when you have only one.
It will be created and be available everywhere in the Jamal file, even if the first use of Ruby was in a local scope.

You can overwrite the name of the shell, defining the user-defined macro
`{%shellNamingMacro%}`, or using the macro option of the same name or the alias `shell`.

It can be done using the usual built-in macro `define`, as in the example
{%@define myLocalShell=myLocalShell%}
{%#comment
we need this here, to be safe
{%sample/
{@undefine {%shellNamingMacro%}}
%}{%output%}
%}\
{%sample/
{@ruby:eval $z = 13}
{@define {%shellNamingMacro%}={%myLocalShell%}}
{@ruby:eval $z}
%}

will result in the output:

{%output%}

The reason for this is that the first evaluation is executed in a shell named `{%defaultShellName%}`.
The second evaluation, however, runs in a different shell, named `{%myLocalShell%}`.

[NOTE]
====
Note that the `try` macro use is `{@try...}` and NOT `{#try...}`.
We have to use the ' # ' character to evaluate the content of a built-in macro before the macro invocation.
In the case of the `try` macro, we want to evaluate the content, but NOT BEFORE the `try` macro invocation.
If we use the macro in the form `{#try...}`, the content is evaluated before starting the macro `try`.
If there is any error, the macro `try` cannot catch it because it has not started yet.
On the other hand, using `{@try...}` will pass the content unevaluated, and the macro `try` will evaluate it and catch the errors.

It is not Ruby module specific; however, it is a widespread mistake, hence described here.
====

There is a resource file named {%#file {%@define fileFormat=`$name`%}{%@define root=src/main/resources/%}ruby.jim%}.
You can import this file and then use the macros defined in it.
The previous example will look the following:

{%#comment
we need this here because all samples run in the same processor, and we renamed the shell
{%sample/
{@undefine {%shellNamingMacro%}}
%}{%output%}
%}

{%sample/
{@import res:ruby.jim}
{@ruby:eval $z = 13}
{shell={%myLocalShell%}}
{@ruby:eval $z}
%}

will result in the output:

{%output%}

It is the same as the previous one, not surprisingly.

All Ruby macros are link:../GLOSSARY.adoc[inner scope dependent], which means that you can define the macro `{%shellNamingMacro%}` inside the Ruby macro call.
In that case, the definition following the Jamal rules will be local to the Ruby macro.

For example
{%#comment
we need this here because all samples run in the same processor, and we renamed the shell
{%sample/
{@undefine {%shellNamingMacro%}}
%}{%output%}
%}

{%sample/
{@import res:ruby.jim}
{@ruby:eval $z = 13}
{#ruby:eval {shell={%myLocalShell%}}$z}
{@ruby:eval $z = 13}
%}

will result in the output:

{%output%}

The second evaluation is performed in a different shell, but the definition of the shell name is local to the macro `ruby:eval`.
(What is more, it is local to the `try` macro.)

The last example can also be written as

{%#comment
we need this here because all samples run in the same processor, and we renamed the shell
{%sample/
{@undefine {%shellNamingMacro%}}
%}{%output%}
%}

{%sample/
{@ruby:eval $z = 13}
{#ruby:eval (shell={%myLocalShell%})$z}
{@ruby:eval $z = 13}
%}

will result in the same output:

{%output%}

[[Sample]]
=== Sample Application, Converting this `README.adoc`

{%@define $lang=ruby%}
{%@define $Lang=Ruby%}
{%@include ../scriptingReadme.adoc.jim%}

[source,java]
----
{%#trimLines
{%@snip Ruby_Jamal_Doc_Execution
        final var processor = new Processor("{%", "%}");
        final var in = FileTools.getInput(directory + "/" + fileName + "." + ext + ".jam", processor);
        final var shell = Shell.getShell(processor, Shell.DEFAULT_RUBY_SHELL_NAME);
        shell.property("$processor", new MyProcessor());
        processor.defineGlobal(shell);
        final var result = processor.process(in);
%}
%}
----
It is almost a standard invocation of the Jamal processor.
The only difference is that it creates a Ruby container using the default container name and injects a Jamal `MyProcessor` instance into the container with the name `$processor`.
When Jamal runs any Ruby code running in the same container will be able to access the processor.

The `MyProcessor` class is an inner class inside the test class, and it reads as the following:

[source,java]
----
{%#trimLines
{%@snip MyProcessor
    public static class MyProcessor {
        final Processor processor = new Processor("{", "}");

        public String process(String s) throws BadSyntax {
            return processor.process(Input.makeInput(s));
        }
    }
%}
%}
----

This class is a wrapper, that provides the method `{%@java:method javax0.jamal.ruby.TestConvertRubyReadme$MyProcessor#process%}()` with a string argument.
It can directly be invoked from Ruby.

Using this possibility the user defined macros `sample` and `output` are simply the following:
{%@snip:collect from="readmemacros.jim"%}

* `sample`

[source]
----
{%#replaceLines replace="/^(.*)$/    $1/"
{%@snip Ruby_sample_user_defined_macro%}%}
----

This macro saves the sample code to the global Ruby variable `$lastCode calling the macro `ruby:property`.
The script removes the leading and trailing newline character from the sample, if there is any.
Finally, the script returns the resulted string, which is placed between the Asciidoc code display.

* `output`

[source]
----
{%#replaceLines replace="/^(.*)$/    $1/"
{%@snip Ruby_output_user_defined_macro%}%}
----

This macro uses the saved property `lastCode` to access the text of the last sample.
It invokes the processor to process it.
The result value of the macro is the output of the processor.

This chapter discussed how documentation should be "programs" to avoid redundancy in the source and to support consistency.
After that, we made a short detour discussing the Jamal snippets, which have complete documentation in the file link:{%@file ../jamal-snippet/README.adoc%}[Snippet README].
We also discussed how the documentation conversion works with snippets and Jamal samples in the Snippet module.
Finally, we had a look at how simpler it is using the Ruby integration.

NOTE: We copied none of the sample codes manually in the source `README.adoc.jam`.

It demonstrates the power and flexibility of Jamal enhanced with the Ruby integration.
If you like the idea, but Ruby is not your favorite scripting language, have a look at the link:{%@file ../jamal-groovy/README.adoc%}[Groovy Integration] documentation and give it a try.

{%@snip:update%}
[WARNING]
--
* There were 2 syntax errors processing the Jamal input:
* 1. There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
* 2. There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8
--
[source]
----
There were 2 syntax errors processing the Jamal input:
1. There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
2. There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8

javax0.jamal.api.BadSyntax: There were 2 syntax errors processing the Jamal input:
1. There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
2. There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8

	at javax0.jamal.engine.Processor.closeProcess(Processor.java:907)
	at javax0.jamal.engine.Processor.process(Processor.java:183)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:338)
	at javax0.jamal.asciidoc.JamalPreprocessor.runJamalInProcess(JamalPreprocessor.java:201)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:132)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy.process(PreprocessorProxy.java:94)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy$INVOKER$i$2$0$process.call(PreprocessorProxy$INVOKER$i$2$0$process.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodTwoOrN.call(JavaMethod.java:1035)
	at org.jruby.RubyMethod.call(RubyMethod.java:124)
	at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:376)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther2:\=\{\}(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$block$parse$1(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
	at org.jruby.runtime.Block.yield(Block.java:188)
	at org.jruby.RubyArray.each(RubyArray.java:1865)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:152)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:161)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther24:each(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$method$parse$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:149)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.invokeOther83:parse(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.RUBY$method$load$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:175)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:222)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:226)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.invokeOther34:load(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.RUBY$method$convert$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.RubyClass.finvoke(RubyClass.java:784)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:311)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:336)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:331)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:816)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:782)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:771)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:149)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: javax0.jamal.api.BadSyntaxAt: There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
		at javax0.jamal.api.BadSyntaxAt.when(BadSyntaxAt.java:92)
		at javax0.jamal.engine.util.MacroQualifier.getMacro(MacroQualifier.java:79)
		at javax0.jamal.engine.util.MacroQualifier.<init>(MacroQualifier.java:50)
		at javax0.jamal.engine.Processor.processMacro(Processor.java:249)
		at javax0.jamal.engine.Processor.process(Processor.java:169)
		... 59 more
	Suppressed: javax0.jamal.api.BadSyntaxAt: There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8
		at javax0.jamal.api.BadSyntaxAt.when(BadSyntaxAt.java:92)
		at javax0.jamal.engine.util.MacroQualifier.getMacro(MacroQualifier.java:79)
		at javax0.jamal.engine.util.MacroQualifier.<init>(MacroQualifier.java:50)
		at javax0.jamal.engine.Processor.processMacro(Processor.java:249)
		at javax0.jamal.engine.Processor.process(Processor.java:169)
		at javax0.jamal.engine.Processor.lambda$evaluateUserDefinedMacro$5(Processor.java:383)
		at javax0.jamal.engine.Processor.safeEvaluate(Processor.java:401)
		at javax0.jamal.engine.Processor.evaluateUserDefinedMacro(Processor.java:383)
		at javax0.jamal.engine.Processor.evalMacro(Processor.java:371)
		at javax0.jamal.engine.Processor.processMacro(Processor.java:262)
		at javax0.jamal.engine.Processor.process(Processor.java:169)
		... 59 more
Suppressed exceptions:
There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17javax0.jamal.api.BadSyntaxAt: There is no built-in macro with the id 'ruby:property' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/25:17
	at javax0.jamal.api.BadSyntaxAt.when(BadSyntaxAt.java:92)
	at javax0.jamal.engine.util.MacroQualifier.getMacro(MacroQualifier.java:79)
	at javax0.jamal.engine.util.MacroQualifier.<init>(MacroQualifier.java:50)
	at javax0.jamal.engine.Processor.processMacro(Processor.java:249)
	at javax0.jamal.engine.Processor.process(Processor.java:169)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:338)
	at javax0.jamal.asciidoc.JamalPreprocessor.runJamalInProcess(JamalPreprocessor.java:201)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:132)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy.process(PreprocessorProxy.java:94)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy$INVOKER$i$2$0$process.call(PreprocessorProxy$INVOKER$i$2$0$process.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodTwoOrN.call(JavaMethod.java:1035)
	at org.jruby.RubyMethod.call(RubyMethod.java:124)
	at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:376)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther2:\=\{\}(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$block$parse$1(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
	at org.jruby.runtime.Block.yield(Block.java:188)
	at org.jruby.RubyArray.each(RubyArray.java:1865)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:152)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:161)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther24:each(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$method$parse$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:149)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.invokeOther83:parse(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.RUBY$method$load$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:175)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:222)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:226)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.invokeOther34:load(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.RUBY$method$convert$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.RubyClass.finvoke(RubyClass.java:784)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:311)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:336)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:331)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:816)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:782)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:771)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:149)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8javax0.jamal.api.BadSyntaxAt: There is no built-in macro with the id 'ruby:import' at /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:45 <<< /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam/29:8
	at javax0.jamal.api.BadSyntaxAt.when(BadSyntaxAt.java:92)
	at javax0.jamal.engine.util.MacroQualifier.getMacro(MacroQualifier.java:79)
	at javax0.jamal.engine.util.MacroQualifier.<init>(MacroQualifier.java:50)
	at javax0.jamal.engine.Processor.processMacro(Processor.java:249)
	at javax0.jamal.engine.Processor.process(Processor.java:169)
	at javax0.jamal.engine.Processor.lambda$evaluateUserDefinedMacro$5(Processor.java:383)
	at javax0.jamal.engine.Processor.safeEvaluate(Processor.java:401)
	at javax0.jamal.engine.Processor.evaluateUserDefinedMacro(Processor.java:383)
	at javax0.jamal.engine.Processor.evalMacro(Processor.java:371)
	at javax0.jamal.engine.Processor.processMacro(Processor.java:262)
	at javax0.jamal.engine.Processor.process(Processor.java:169)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:338)
	at javax0.jamal.asciidoc.JamalPreprocessor.runJamalInProcess(JamalPreprocessor.java:201)
	at javax0.jamal.asciidoc.JamalPreprocessor.process(JamalPreprocessor.java:132)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy.process(PreprocessorProxy.java:94)
	at org.asciidoctor.jruby.extension.processorproxies.PreprocessorProxy$INVOKER$i$2$0$process.call(PreprocessorProxy$INVOKER$i$2$0$process.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodTwoOrN.call(JavaMethod.java:1035)
	at org.jruby.RubyMethod.call(RubyMethod.java:124)
	at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:376)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther2:\=\{\}(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$block$parse$1(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
	at org.jruby.runtime.Block.yield(Block.java:188)
	at org.jruby.RubyArray.each(RubyArray.java:1865)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:152)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:161)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.invokeOther24:each(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.document.RUBY$method$parse$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:149)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.invokeOther83:parse(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.load.RUBY$method$load$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:175)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:222)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:226)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.invokeOther34:load(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_18.lib.asciidoctor.convert.RUBY$method$convert$0(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.RubyClass.finvoke(RubyClass.java:784)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:311)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:336)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:331)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:816)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:782)
	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:771)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:149)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
sed -i jam '' /Users/verhasp/github/jamal/jamal-ruby/README.adoc.jam
----
