= Jamal AsciiDoc Extension

This document is the readme file for the Jamal Asciidoc extension version `1.11.3-SNAPSHOT`.

== Introduction

This Jamal module provides a extension for Asciidoc.
The extension is a preprocessor extension reading the input of the asciidoc document before the actual transformation of Asciidoc happens.
Using this extension you can configure your asciidoc converted to invoke the Jamal preprocessing as part of the asciidoc conversion.

The major use case is using the extension together with the IntelliJ IDEA plugin for Asciidoc.
Installing this extension you can see the rendered and Jamal preprocessed Asciidoc result on the right editor pane while editing your `.adoc.jam` file.

It is not intended to be used as an exclusive way to execute Jamal when processing Asciidoc.

Maintaining a separate `.adoc.jam` and the generated `.adoc` file is the good solution.
For example, when you maintain your project on GitHub the `.adoc` file is rendered by the platform on the file.
This can only be done if you have the Jamal preprocessed and generated `.adoc` file uploaded to GitHub.

== Installation with IntelliJ IDEA

[NOTE]
====
Asciidoc plugin is a plugin into IntelliJ.
The code in this module is not an IntelliJ plugin.
It is an extension to Asciidoctor, which itself is an IntelliJ plugin.
This way this extension is an extension of a plugin.
You cannot install this extension as a separate plugin to IntelliJ.
It works only with the Asciidoc plugin in IntelliJ.
====


To use the plugin together with the IntelliJ Asciidoc plugin you need  the file `jamal-asciidoc-1.11.3-SNAPSHOT-jamal-asciidoc-distribution.zip`.
Extract the content of this zip file into your projects `.asciidoctor/lib` folder.
Restart IntelliJ and when it asks about the plugin say that you trust this plugin.
Start editing the `.adoc.jam` file and have a look at the right pane at the rendered document.

== Modules

When using Jamal you probably want to use extra built-in macros in addition to the core module's.
The ZIP file you extracted to the `.asciidoctor/lib` folder contains the following modules:



* `jamal-extensions`

* `jamal-snippet`

* `jamal-test`

* `jamal-scriptbasic`

* `jamal-groovy`

* `jamal-ruby`

* `jamal-plantuml`

* `jamal-debug`

* `jamal-jamal`

* `jamal-yaml`

* `jamal-io`

* `jamal-assertions`


This is essentially all the macro modules that come with Jamal by default.
If you want to use additional modules all you have to do is copying the `.jar` files to the `.asciidoctor/lib` folder.
The IntelliJ Asciidoc plugin will automatically load the modules.

== Error Handling

When the asciidoc conversion finds an error in the document it still renders the document and creates a preview.
This can be done because asciidoc is a format where the cohesion between the different parts is not too strong.
If there is an error at some point  in the code the rest of the document may still be rendered and will look the same.

Jamal, on the other hand, is a complex macro language.
It is very likely that it is not possible to reasonably process the input after some error.
If there is an error in the input, the Jamal processor will not produce an output.
As a most usable approach the extension will result the input without preprocessing but enriched with error messages.

The extension will insert the error message given by the Jamal processor to the start of the document as a WARNING admonition.
It will also insert the same admonition at the line where the error is as well as, at the end of the document.
The error message at the end of the document is followed by a source block including the full stack trace.

This way it may be easier to find the error in the document and still see some preview while the input is erroneous.

