#! /bin/bash
npm version `grep '^VERSION=' ../version.jim|cut -d'=' -f2 | cut -d' ' -f1`
npm run build
rm -rf ../jamal-debug/src/main/resources/ui/static/css
rm -rf ../jamal-debug/src/main/resources/ui/static/js
cp -R ./build/* ../jamal-debug/src/main/resources/ui/
rm ../jamal-debug/src/main/resources/ui/static/css/*.map
rm ../jamal-debug/src/main/resources/ui/static/js/*.map
git add --all ../jamal-debug/src/main/resources
