#! /bin/bash
resources=$(realpath ..)/jamal-debug/src/main/resources
ui=$resources/ui
static=$ui/static
css=$static/css
js=$static/js
echo "Building the new version of the debugger UI"
echo
echo "Setting the version from ../version.jim"
VERSION="$(grep '^VERSION=' ../version.jim|cut -d'=' -f2 | cut -d' ' -f1)"
npm version "$VERSION" &> /dev/null
echo "Building the version $VERSION"
npm run build &> /dev/null
echo "build done"
echo "removing old css files from $css"
rm -rf $css
echo "removing old js files from $js"
rm -rf $js
echo "copying new files to $ui"
cp -R ./build/* $ui
echo "removing map files $css"
rm $css/*.map
echo "removing map files $js"
rm $js/*.map
echo "adding new files to git"
git add --all "$resources"
echo "done... you can now build the main project including the new version of the debugger UI"
