= Jamal OpenAI module



== Introduction

With the OpenAI module you can include text generated by the OpenAI API into your Jamal documents.
That way you can ask OpenAI to complete your text, answer questions and so on.
The completed text or picture has to be reviewed.
You can use the OpenAI module macros to seal the results.
Sealed results are stored in cache files and do not change, and also do not require any API calls.
That way you can freely change the parts of the document, which do not depend on the OpenAI API results without needing to call the API again.

Calling OpenAI API is not free and can be abused.
Therefore, the OpenAI module is an unsafe module.
It means that the Jamal document has to load it using the `maven:load` macro and the module has to be configured on your machine as trusted.
Starting to use this module is not simple.

The OpenAI API is also complex adding to the complexity of the module structure.
The module defines only two low level macros, `openai:post` and `openai:get`.
These are used by higher level macros.
This structure makes it possible to follow the changes of the OpenAI API without the need of a new release of the macro module.

== Loading the module

The module is a so-called unsafe module.
Unsafe modules are not loaded by default by the core applications, like the command line version of Jamal, the asciidoc preprocessor or the Maven extension.
Other applications, like the Maven plugin implementation can be configured by the user to load any module, safe or unsafe.

The usual way to load an unsafe module is using the `maven:load` macro.
This macro needs the maven coordinates of the module to be loaded.
It also requires that the module is configured for the local Jamal installation.
The configuration tries to avoid arbitrary external modules loaded during Jamal document processing.
For more information about how to configure `maven:load` please read the link:../jamal-maven-load/README.adoc[documentation of the macro itself].


To load the macros use the following line in your Jamal document:

  {@maven:load com.javax0.jamal:jamal-openai:1.12.7-SNAPSHOT}\

The module defines macros on three levels.
The low level is the pure API access implemented with HTTP POST and GET.
The service level exposes the individual API calls and result the returning JSONS.
The high level macros are the most convenient to use.
They ask for the meaningful parameter and return the part of the resulting JSON that is the answer.

We have already loaded the macros into the jamal processor, but before using it they also need configuration.

== Configuration

Jamal and the different macro libraries follow the philosophy of convention over configuration.
Macro packages usually do not need configuration.
The OpenAI module is an exception, because you need to configure your OpenAI API key.
The API key is used to authenticate your requests to the OpenAI API.
You can get your API key from the OpenAI dashboard.

The macro library is designed to use the Jamal supported environment based configuration.
This configuration is looking for configuration values in:

* Java system properties,
* Environment variables,
* Configuration files.

in this order. The `OPENAI_API_KEY` environment variable is used to configure the API key.
When looking for Java system properties, Jamal replaces the `_` character with `.` and converts the name to lower case.
Thus, the environment variable `OPENAI_API_KEY` is converted to the Java system property `openai.api.key`.

There is another configuration key: `OPENAI_ORGANIZATION`.
This is the organization ID of your OpenAI account.
This configuration key is optional.

If the values are not specified in the system properties or environment variables, the configuration file is searched.
The configuration file is a properties file, `~/.jamal/settings.properties`.
My current configuration file looks like this:

  $ cat ~/.jamal/settings.properties
  openai.api.key=sk-GafL87XwJMDMluDGHf7bT3BlbkFZQf27uCVkIbkDbzLUn@Pt
  maven.load.include=com.javax0.jamal:jamal-openai:*

(Not a real key, though.)

== Low Level Macros

The module defines only two built-in macros:

* `openai:get`, and
* `openai:post`.

These macros are used to execute low level API calls to the OpenAI API.
You will not use these macros directly in your document.

What you will use are the Service macros or the High Level macros.
These are defined in the `openai.jim` resource file.

These are defined in the `openai.jim` resource file.

NOTE: Jamal include files have the extension `.jim` instead of `.jam` by convention.

Because the macros were loaded via the `maven:load` macro, the `openai.jim` file is not on the regular classpath.
Because of that the special form of the `res:` resource syntax has to be used naming a macro from the package where the resource file is.

  {@import res:`openai:get`openai.jim}

After you imported this file you can use the macros defined in it.

== Service Macros

Service macros use the built-in `openai:post` and `openai:get` macros to execute the API calls.
They are defined in the `openai.jim` resource file.

=== `openai:query_models`

This is the simplest macro.
It needs no parameters, and it returns a list of all available models.

  {@openai:query_models}

=== `openai:query_model(model)`


== High Level Macros
