= Jamal IO module

Using this module, you can handle files from a Jamal source code.
You can

* create a file,

* write text to the file,

* create directories,

* delete directories, files and

* you can print messages to the standard output or to the standard error.

To use this module, you have to add the dependency to your Maven project, as:

[source,xml]
----
<dependency>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-io</artifactId>
    <version>1.7.5-SNAPSHOT</version>
</dependency>

----

Following that, you can use the macros


. <<write,`io:write`>>
. <<remove,`io:remove`>>
. <<mkdir,`io:mkdir`>>
. <<print,`io:print`>>


macros.

== Macros implemented in the package

[[write]]
=== i. `io:write`


Using this macro you can write some text into a file.
The format of the macro is

[source]
----
{@io:write (options) text to write into the file}
----

The macro will write the input of the macro to a text file.
The name of the file and write mode can be controlled using options.
The options are:

* `io:outputFile` (aliases `io:output`, `output`, `io:file`, `file`) can define the name of the file.

Use the user defined macro if you want to write several different segments to the file, and you do not want to specify the name of the file every the time.

* `io:append` (alias `append`) is a boolean option controlling if the content should be appended, or the file has to be truncated.
The default value is to truncate the file.

* `io:mkdir` (alias `mkdir`) is a boolean option controlling if the directory where the file has to be is created before writing the file if it does not exist.
The default is not to create the file.


Note that the option can be defined as a user defined macro or as an option using the `{@option ...}` macro.
The aliases can only be used on the macro itself after the name of the macro between `(` and `)` characters.

[[remove]]
=== ii. `io:remove`


This macro can be used to remove a file or directory.
The format of the macro is

[source]
----
{@io:remove options}
----

The options are:

* `io:outputFile` (aliases `io:output`, `output`, `io:file`, `file`) can define the name of the file.

* `io:recursive` (alias `recursive`) is a boolean option controlling if the deletion should be recursive

Note that this macro reads the options directly from the input, and they are not enclosed between `(` and `)` characters.


Note that the option can be defined as a user defined macro or as an option using the `{@option ...}` macro.
The aliases can only be used on the macro itself after the name of the macro between `(` and `)` characters.

[[mkdir]]
=== iii. `io:mkdir`


This macro can be used to create a directory.
The format of the macro is

[source]
----
{@io:mkdir options}
----

The options are:

* `io:outputFile` (aliases `io:output`, `output`, `io:file`, `file`) can define the name of the file.

* `io:recursive` (alias `recursive`) is a boolean option controlling if the deletion should be recursive

Note that this macro reads the options directly from the input, and they are not enclosed between `(` and `)` characters.


Note that the option can be defined as a user defined macro or as an option using the `{@option ...}` macro.
The aliases can only be used on the macro itself after the name of the macro between `(` and `)` characters.

[[print]]
=== iv. `io:print`


This macro can be used to print some text to the standard output or to the standard error.
The format of the macro is

[source]
----
{@io:print (options) message to print}
----

There is one option.

* `io:err` (alias `err`) is a boolean option controlling if the message should be written to the standard output or to the standard error.
The default is the standard output.


Note that the option can be defined as a user defined macro or as an option using the `{@option ...}` macro.
The aliases can only be used on the macro itself after the name of the macro between `(` and `)` characters.