= Modules of the Jamal Project
:toc:

This file lists the Jamal modules delivered with each release.
Note that other projects may contain other Jamal modules delivered independently of the modules in this project.


== Module Categories
The different modules fall into one of the four categories:




=== core
__core__ belongs to the core of Jamal, and it is an essential part of the Jamal macro processor

=== embed
__embed__ is a module, which uses Jamal and makes it possible to use Jamal in some specific environment.
Such a module may or may not contain macros.
If it does, the macros are specific to the embedding environment.

=== macro
__macro__ is a package containing macro implementations.
Jamal comes with a limited set of built-in macros.
Specific features are supported by macros implemented in macro libraries.
To use those libraries, they have to be on the module path or on the class path.

=== debugger
__debugger__ is the module implementing the debugger interface of Jamal.
There can be several modules implementing this interface.
Currently, there are two.
One provides a TCP interface for an external debugger.
This implementation is for reference purposes, and it is not feature complete.
The other implementation provides a REST interface towards a debugger client, and it also contains a REACT.js based client.

=== input
__input__ is a module implementing an input handler for Jamal.
Input handlers are loaded via the service loader and can load resource files, maven artifacts, files from JAR archives, etc.



== Modules
=== 1. link:https://github.com/verhas/jamal/blob/master/jamal-all/README.adoc[ALL] ^_core_^


This module contains no code.
It can be used as a Maven dependency when there is a need to use all Jamal modules.
It can be a convenience supporting some laziness, but in some cases it may be a necessity.

=== 2. link:https://github.com/verhas/jamal/blob/master/jamal-api/README.adoc[API] ^_core_^


`jamal-api` contains interfaces that the Jamal macros and the processing implements.
Some interfaces implement some default methods.
This module contains the `BadSyntax` and `BadSyntaxAt` exception classes, which are thrown when there is some error in the processing.

=== 3. link:https://github.com/verhas/jamal/blob/master/jamal-asciidoc/README.adoc[ASCIIDOC] ^_embed_^


`jamal-asciidoc` is an ASCIIDOCTOR preprocessor preprocessing the text input using Jamal.
The primary use of this module is to install it into WYSIWYG editors that support asciidoctor.
For example, you can use Jamal via this module in IntelliJ.

=== 4. link:https://github.com/verhas/jamal/blob/master/jamal-asciidoc258/README.adoc[ASCIIDOC258] ^_embed_^


This module is a dependency for the `jamal-asciidoc` module.
It provides backward compatibility for the AsciidoctorJ 2.X.X versions.

=== 5. link:https://github.com/verhas/jamal/blob/master/jamal-assertions/README.adoc[ASSERTIONS] ^_macro_^


Contains macros that can be used to perform assertions.
An assertion is usually a constraint checking some string values.
When the assertion fails, the processing will give an error.
You can use assertions to enforce document consistency.

=== 6. link:https://github.com/verhas/jamal/blob/master/jamal-cmd/README.adoc[CMD] ^_embed_^


This module is the command line version of Jamal.
This module has a `public static void main()`, a shell script to start Jamal.
The module also supports jbang to start Jamal.
The module has dependencies for ALL the macro modules so that you can use any macro in your files.
In addition to that, it incorporates the word module to process Microsoft Word documents from the command line.

=== 7. link:https://github.com/verhas/jamal/blob/master/jamal-core/README.adoc[CORE] ^_macro_^


Implements the core built-in macros.

=== 8. link:https://github.com/verhas/jamal/blob/master/jamal-debug/README.adoc[DEBUG] ^_debugger_^


This module implements two debuggers.
The Jamal engine does not contain a debugger itself.
The engine has an SPI that the debuggers can implement and hook into the evaluation process.
This module implements a TCP-based debugger for reference purposes and one with a REST interface.
The TCP implementation is not feature complete and serves reference purposes as a simple implementation of the SPI.
The REST implementation includes a REACT.js based web client, and it is a fully usable debugger.

=== 9. link:https://github.com/verhas/jamal/blob/master/jamal-doclet/README.adoc[DOCLET] ^_embed_^


With this module you can use Jamal macros in your JavaDoc documentation.

=== 10. link:https://github.com/verhas/jamal/blob/master/jamal-engine/README.adoc[ENGINE] ^_core_^


Jamal core functionality implementation.

=== 11. link:https://github.com/verhas/jamal/blob/master/jamal-extensions/README.adoc[EXTENSIONS] ^_macro_^


Experimental macros, nothing is guaranteed.
Usually macros in this module get into their own modules later.

=== 12. link:https://github.com/verhas/jamal/blob/master/jamal-groovy/README.adoc[GROOVY] ^_macro_^



Use Groovy code in your macros using the macros implemented in this module.

=== 13. link:https://github.com/verhas/jamal/blob/master/jamal-io/README.adoc[IO] ^_macro_^


This module implements macros that can read and write files and can start external processes.
There is a special security consideration for this module and how you MUST configure the external processes to run.

=== 14. link:https://github.com/verhas/jamal/blob/master/jamal-jamal/README.adoc[JAMAL] ^_macro_^


Special macros to embed Jamal into Jamal.
This is a module used mainly to demonstrate how Jamal works and to have Jamal macros as examples in a Jamal processed file.

=== 15. link:https://github.com/verhas/jamal/blob/master/jamal-markdown/README.adoc[MARKDOWN] ^_macro_^


A macro that processes its input as markdown and results the HTML output.
The main purpose of this macro package is to use it together with the JavaDoc embedding.

=== 16. link:https://github.com/verhas/jamal/blob/master/jamal-maven-extension/README.adoc[MAVEN-EXTENSION] ^_embed_^


This module implements a Maven extension (not a plugin, that is the next module).
With this you can use the Maven build tool controlled by a `pom.jam` file, which is a `pom.xml` file possibly extended with Jamal macros.

=== 17. link:https://github.com/verhas/jamal/blob/master/jamal-maven-input/README.adoc[MAVEN-INPUT] ^_input_^


This module implements a Maven input handler making files in Maven artifact JAR files available for Jamal processing.

=== 18. link:https://github.com/verhas/jamal/blob/master/jamal-jar-input/README.adoc[JAR-INPUT] ^_debugger_^


This module implements a JAR input handler making files in local JAR files available for Jamal processing.

=== 19. link:https://github.com/verhas/jamal/blob/master/jamal-maven-load/README.adoc[MAVEN-LOAD] ^_macro_^


This module implements a macro that can load a Maven artifact and loads the built-in macros implemented in the JAR file.

=== 20. link:https://github.com/verhas/jamal/blob/master/jamal-maven-plugin/README.adoc[MAVEN-PLUGIN] ^_embed_^


This module implements a maven plugin, so you can start Jamal processing from inside a build process.

=== 21. link:https://github.com/verhas/jamal/blob/master/jamal-mock/README.adoc[MOCK] ^_macro_^


This module implements the macro `mock` to mock some built-in macros in a test environment where the given macro may not be available or behaves differently.
Using `mock` you can create tests for your macro packages.

=== 22. link:https://github.com/verhas/jamal/blob/master/jamal-plantuml/README.adoc[PLANTUML] ^_macro_^


This module implements a macro that invokes PlantUML, generates the graphical file from the source code that you can reference as an image from your documentation.

=== 23. link:https://github.com/verhas/jamal/blob/master/jamal-ruby/README.adoc[RUBY] ^_macro_^



Use Ruby code in your macros using the macros implemented in this module.

=== 24. link:https://github.com/verhas/jamal/blob/master/jamal-scriptbasic/README.adoc[SCRIPTBASIC] ^_macro_^



Use BASIC code in your macros using the macros implemented in this module.

=== 25. link:https://github.com/verhas/jamal/blob/master/jamal-prog/README.adoc[PROG] ^_macro_^


This module implements a simple BASIC like language integrated into Jamal.

=== 26. link:https://github.com/verhas/jamal/blob/master/jamal-snippet/README.adoc[SNIPPET] ^_macro_^


This module implements macros to help document programs.
It includes advanced snippet handling, text transformation, text assertions, and many other features.

=== 27. link:https://github.com/verhas/jamal/blob/master/jamal-test/README.adoc[TEST] ^_core_^


This module contains only test code.
During the build, these integration tests check the consistency of the application.

=== 28. link:https://github.com/verhas/jamal/blob/master/jamal-testsupport/README.adoc[TESTSUPPORT] ^_core_^


This module contains classes that you can use to write unit tests to check the implementation of some macros.

=== 29. link:https://github.com/verhas/jamal/blob/master/jamal-tools/README.adoc[TOOLS] ^_core_^


This module implements some auxiliary classes for the engine.
It could be part of the engine.

=== 30. link:https://github.com/verhas/jamal/blob/master/jamal-word/README.adoc[WORD] ^_embed_^


This implementation can read DOCX format files, process the Jamal macros and generate DOCX output.
This module is included in the command line version, thus you can convert Microsoft Word documents from the command line version of Jamal.

=== 31. link:https://github.com/verhas/jamal/blob/master/jamal-json/README.adoc[JSON] ^_macro_^


This module implements macros that support the reading and processing of JSON format data.

=== 32. link:https://github.com/verhas/jamal/blob/master/jamal-kotlin/README.adoc[KOTLIN] ^_macro_^


This module provides a complimentary API to ease the creation of macros in Kotlin.

=== 33. link:https://github.com/verhas/jamal/blob/master/jamal-kotlin-testsupport/README.adoc[KOTLIN-TESTSUPPORT] ^_macro_^


This module provides test support for macros implemented in Kotlin.

=== 34. link:https://github.com/verhas/jamal/blob/master/jamal-yaml/README.adoc[YAML] ^_macro_^


This module implements macros that support the reading and processing of YAML format data.
It may be useful when you have to maintain large YAML data files.
Using these macros, you can split up a Yaml file into smaller pieces and use macros to simplify repetitive parts.

=== 35. link:https://github.com/verhas/jamal/blob/master/jamal-openai/README.adoc[OPENAI] ^_macro_^


Macros implementing interface to OpenAI.

=== 36. link:https://github.com/verhas/jamal/blob/master/jamal-java/README.adoc[JAVA] ^_debugger_^


Experimental module integrating the Java compiler into Jamal as macros.

=== 37. link:https://github.com/verhas/jamal/blob/master/jamal-debug-ui/README.adoc[DEBUG-UI] ^_debugger_^


This is not a module.
The code in the directory `jamal-debug-ui` contains the REACT.js based ui for the debugger.

=== 38. link:https://github.com/verhas/jamal/blob/master/jamal-docker/README.adoc[DOCKER] ^_embed_^


This is not a module.
The code in the directory `jamal-docker` contains a Dockerfile to build a Docker image with Jamal.



