= This file is a manual test for `units.jim`

The symbolic names and the unicode character images in the rendered output should match.

The reason to have these macros is to help the maintenance of documents that are restricted to ASCII characters.
It may also be easier to type the symbolic names than the unicode characters.

Conventions in the symbolic names:

* The unit name starts with the prefix `unit:`.
It also makes the macro global.

* The name of the unit is usually the unit preceded by metrix prefixes.
Latin letters denote these prefixes except `µ` for `micro`.
In the case of micro we use the letter `u`.

* When the unit is a fraction, the slash is replaced by `_p_`.
This middle part stands for __"per"__.

* The capitalization of the letters in the unit name is the same as in the unicode picture of the character.

* Not all SI units and SI prefixes are available in Unicode.

* The characters that are in the code page but are not unit symbols are not included in this file.

== Here are the units


* hPa ㍱
* da ㍲
* AU ㍳
* bar ㍴
* oV ㍵
* pc ㍶
* pA ㎀
* nA ㎁
* uA ㎂
* mA ㎃
* kA ㎄
* KB ㎅
* MB ㎆
* GB ㎇
* cal ㎈
* kcal ㎉
* pF ㎊
* nF ㎋
* uF ㎌
* ug ㎍
* mg ㎎
* kg ㎏
* Hz ㎐
* kHz ㎑
* MHz ㎒
* GHz ㎓
* THz ㎔
* ul ㎕
* ml ㎖
* dl ㎗
* kl ㎘
* fm ㎙
* nm ㎚
* um ㎛
* mm ㎜
* cm ㎝
* km ㎞
* m2 ㎡
* km2 ㎢
* mm3 ㎣
* cm3 ㎤
* m3 ㎥
* km3 ㎦
* m_p_s ㎧
* m_p_s2 ㎨
* Pa ㎩
* kPa ㎪
* MPa ㎫
* GPa ㎬
* rad ㎭
* rad_p_s ㎮
* rad_p_s2 ㎯
* ps ㎰
* ns ㎱
* us ㎲
* ms ㎳
* pV ㎴
* nV ㎵
* uV ㎶
* mV ㎷
* kV ㎸
* MV ㎹
* pW ㎺
* nW ㎻
* uW ㎼
* mW ㎽
* kW ㎾
* MW ㎿
* kOhm ㏀
* MOhm ㏁
* Bq ㏃
* cc ㏄
* cd ㏅
* c_p_kg ㏆
* CO ㏇
* dB ㏈
* Gy ㏉
* ha ㏊
* in ㏌
* kt ㏏
* mb ㏔
* mil ㏕
* mol ㏖
* pH ㏗
* ppm ㏙
* sr ㏛
* Sv ㏜
* Wb ㏝