== Thin XML Format






== Introduction

Thin XML is a format mapped to XML effortlessly and straightforwardly, but it contains fewer characters and is more readable.
The thin XML format lets you leave the closing tags.
Instead of the closing tags, it introduces positioning.

It is somewhat similar to what the Python language is doing compared to other languages.
Many languages use explicit closing for complex constructs, like adding a `}` to the end of a block or using the `end` keyword.
Python starts to write with the previous indentation following a block.

Thin XML does the same.
To ease understanding here is a simple example:

[source]
----
project>
  modelVersion>4.0.0
  name>jamal snippet
  packaging>jar
  groupId>com.javax0.jamal
  artifactId>jamal-snippet
  version>1.10.3-SNAPSHOT
  parent>
    groupId>com.javax0.jamal
    artifactId>jamal-parent
    version>1.10.3-SNAPSHOT
    relativePath>../jamal-parent
----

It is the same as the standard XML in the following way:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-snippet</artifactId>
    <version>1.10.3-SNAPSHOT</version>
    <parent>
        <groupId>com.javax0.jamal</groupId>
        <artifactId>jamal-parent</artifactId>
        <version>1.10.3-SNAPSHOT</version>
        <relativePath>../jamal-parent</relativePath>
    </parent>
</project>
----


The tags `modelVersion`, `name`, and so on are all tabbed deeper than `project`; thus, they are tags inside the `project` tag.
The `parent` also has children, which are tabbed deeper.

== Thin XML Tabbing

The tabbing can go back and forth many times.
If we move the `groupId`, `artifactId`, and `version` tags to follow the `parent` tag, but with the same tab depth:

[source]
----
project>
  modelVersion>4.0.0
  name>jamal snippet
  packaging>jar
  parent>
    groupId>com.javax0.jamal
    artifactId>jamal-parent
    version>1.10.3-SNAPSHOT
    relativePath>../jamal-parent
  groupId>com.javax0.jamal
  artifactId>jamal-snippet
  version>1.10.3-SNAPSHOT
----

we get the following:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <parent>
        <groupId>com.javax0.jamal</groupId>
        <artifactId>jamal-parent</artifactId>
        <version>1.10.3-SNAPSHOT</version>
        <relativePath>../jamal-parent</relativePath>
    </parent>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-snippet</artifactId>
    <version>1.10.3-SNAPSHOT</version>
</project>
----


The XML text, like the `4.0.0` model version, can be on the same line as the tag, following it, or on the following lines.

[source]
----
project>
  modelVersion>4.0.0
  name>jamal snippet
  packaging>jar
  description>
    The snippet library for the jamal language.
    It also contains the xmlFormat macro that can convert from thin XML to regular XML.
  parent>
    groupId>com.javax0.jamal
    artifactId>jamal-parent
    version>1.10.3-SNAPSHOT
    relativePath>../jamal-parent
  groupId>com.javax0.jamal
  artifactId>jamal-snippet
  version>1.10.3-SNAPSHOT
----

we get the following:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <description>
        The snippet library for the jamal language.
        It also contains the xmlFormat macro that can convert from thin XML to regular XML.
    </description>
    <parent>
        <groupId>com.javax0.jamal</groupId>
        <artifactId>jamal-parent</artifactId>
        <version>1.10.3-SNAPSHOT</version>
        <relativePath>../jamal-parent</relativePath>
    </parent>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-snippet</artifactId>
    <version>1.10.3-SNAPSHOT</version>
</project>
----


It is essential that the tabulation, even, in this case, has to be the same.
Making a mistake and starting the text too much to the left will close the tag.

[source]
----
project>
  packaging>jar
  description>
    The snippet library for the jamal language.
 Misaligned text closes the tag.
  parent>
    groupId>com.javax0.jamal
    description>
      The parent library for the jamal language.
 This misplaced text will close the parent tag also.
    relativePath>../jamal-parent
  groupId>com.javax0.jamal
  artifactId>jamal-snippet
  version>1.10.3-SNAPSHOT
----

will be

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <packaging>jar</packaging>
    <description>
        The snippet library for the jamal language.
    </description>
        Misaligned text closes the tag.

    <parent>
        <groupId>com.javax0.jamal</groupId>
        <description>
            The parent library for the jamal language.
        </description>
    </parent>
        This misplaced text will close the parent tag also.

    <relativePath>../jamal-parent</relativePath>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-snippet</artifactId>
    <version>1.10.3-SNAPSHOT</version>
</project>
----


== Attributes

The tags in thin XML can also have attributes.
Attributes can be written with `"` separators only.
The `'` character is not allowed as a separator.
If the attribute value does not have space, then the `"` around the value is optional.

[source]
----
project name="prohibited" note="real POM XML does not have attributes">
    packaging>jar
    description format=plain>
     Just some dummy description
  parent>
    groupId value="com.java0.jamal">
  groupId>com.javax0.jamal
  artifactId>jamal-snippet
  version>1.10.3-SNAPSHOT
----

All the tags will have attributes surrounded with `"` characters in the output.

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project name="prohibited" note="real POM XML does not have attributes">
    <packaging>jar</packaging>
    <description format="plain">
        Just some dummy description
    </description>
    <parent>
        <groupId value="com.java0.jamal"/>
    </parent>
    <groupId>com.javax0.jamal</groupId>
    <artifactId>jamal-snippet</artifactId>
    <version>1.10.3-SNAPSHOT</version>
</project>
----


== XML tags in Thin XML

You can also include regular XML tags into think XML.
You can manage the file even if the tabbing would otherwise go excessive.
For example, the following example has gone with tabbing a bit too far to the right:

[source]
----
project>
       modelVersion>4.0.0
       name>jamal snippet
       packaging>jar
       profiles>profile>
                  id>release
                  build>plugins>plugin>
                                    groupId>org.apache.maven.plugins
                                    artifactId>maven-gpg-plugin
                                    version>3.0.1
                                    executions>execution>
                                                 id>sign-artifacts
                                                 phase>verify
                                                 goals>goal>sign
----

It is still correct and works as expected:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----


This example does not achieve the original aim of thin XML to have readable and straightforward XML structured data.
This can be amended including normal XML tags into think XML:

[source]
----
project>
       modelVersion>4.0.0
       name>jamal snippet
       packaging>jar
       profiles>profile>
                  id>release
                  build>plugins>
         <plugin>
           groupId>org.apache.maven.plugins
           artifactId>maven-gpg-plugin
           version>3.0.1
           executions>execution>
                        id>sign-artifacts
                        phase>verify
                        goals>goal>sign
         </plugin>
----

It will result in the same as the previous example:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----


The tabulation of the XML part is not essential and is generally ignored.
After an opening XML tag, the thin XML tabbing is reset and gets back to the previous level after the closing XML tag.
It can start to the left of the previous tags; the already opened tags will not be closed.
The only important rule is that you should align the thin XML inside the opening and closing tags.

The opened XML tag has to be closed with the closing tag.
There is no shorthand for that.

You can embed XML into the thin XML and thin XML into the XML into any level deep.
For example the previous example can also be written as:

[source]
----
project>
       modelVersion>4.0.0
       name>jamal snippet
       packaging>jar
       profiles>profile>
                  id>release
                  build>plugins>
         <plugin>
           groupId>org.apache.maven.plugins
           artifactId>maven-gpg-plugin
           version>3.0.1
           executions>
                            <execution>
   id>sign-artifacts
   phase>verify
   goals>goal>sign
           </execution>
         </plugin>
----

and it still gets the same output:

[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <name>jamal snippet</name>
    <packaging>jar</packaging>
    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----


== Implementation

The thin XML converter is implemented in the Jamal Snippet module and can be used with the macro `xmlFormat`.
The primary purpose of developing thin XML was to support Maven POM shortening while keeping it strictly XML.
You can use the Jamal Maven extension (not a plugin!) to instruct Maven to locate and parse the POM via the extension.